# 소프트맥스(softmax)

- 다중 클래스 분류 문제에 사용되는 활성화 함수, 입력 받은 벡터를 `확률 분포`로 변환
- 각 클래스가 선택될 확률, 0과 1사이에 위치하고 전체 합은 1이 된다. 
- 특히 신경망의 `출력층`에서 유용하게 사용. 

- `여러 카테고리 중 하나를 선택`해야 하는 다중 분류 문제에 적합.  
- 예를 들어, 각 카테고리에 대한 확률을 계산하여 가장 높은 확률을 가진 카테고리를 모델의 예측으로 선택할 수 있다.  

## 장점

- 확실성 제공 : Softmax는 각 클래스에 대한 확률을 계산하여, 모델의 예측에 대한 확실성을 수치로 제공. 결정의 신뢰도를 판단할 수 있다. 
- 다중 클래스 지원 : 여러 클래스 중 하나를 선택하는 문제에 대해, 각 클래스의 확률을 명확하게 제시 할 수 있다.  

## 단점

- 은닉층에서 부적합 : 각 출력이 다른 출력에 의존적이기 때문에, 은닉층에서는 각 결정을 독립적으로 내려야할 때 사용하기 부적합. 
- 이진 분류의 비효율성 : 이진 분류 문제에서는 sigmoid 함수가 더 효율적 일 수 있다. Softmax는 주로 다중 분류 문제에 적합.  



In [1]:
import torch 
logits = torch.tensor([2.0, 1.0, 0.1])

softmax_result = torch.softmax(logits, dim=0)

print(softmax_result)

tensor([0.6590, 0.2424, 0.0986])


In [5]:
import torch.nn as nn
# 선형 층 정의
lilinear_layer = nn.Linear(in_features=3, out_features=1)
input_tensor = torch.randn(1, 3)

linear_output = linear_layer(input_tensor)
print("\nlinear_output:\n", linear_output)

softmax_output = torch.softmax(linear_output, dim=1)
print("\nSoftmax Output:\n", softmax_output)



linear_output:
 tensor([[0.4048]], grad_fn=<AddmmBackward0>)

Softmax Output:
 tensor([[1.]], grad_fn=<SoftmaxBackward0>)
