### Numpy ndarray 개요

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type:',type(array1))
print('array1 array 형태:',array1.shape)

array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type:',type(array2))
print('array2 array 형태:',array2.shape)

array3 = np.array([[1,2,3]])
print('array3 type:',type(array3))
print('array3 array 형태:',array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [3]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim,array2.ndim,array3.ndim))


array1: 1차원, array2: 2차원, array3: 2차원


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) # this type is 'U21' (Unicode string with max length 21)
# numpy converts max length of string to fit the longest string in the list

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) # this type is 'float64'

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)


[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones

In [7]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)



[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [8]:
zero_array = np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### reshape

In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5)
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [13]:
print(array2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [14]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [16]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())
print('array3d shape:',array3d.shape)
print('array3d ndim:',array3d.ndim)

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)
print('array5 ndim:',array5.ndim)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)
print('array6 ndim:',array6.ndim)   

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d shape: (2, 2, 2)
array3d ndim: 3
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array5 ndim: 2
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
array6 ndim: 2


### indexing

* 단일값 추출

In [17]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)
# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


In [18]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [19]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [20]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] )
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


* Slicing

In [21]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [22]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [26]:
print('array2\n', array2d)
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )
print('array2d dimensions:', array2d.ndim)
print('array2d[0] dim :', array2d[0].ndim, 'array2d[1] dim:', array2d[1].ndim)
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

array2
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0] shape: (3,) array2d[1] shape: (3,)
array2d dimensions: 2
array2d[0] dim : 1 array2d[1] dim: 1
[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


* fancy indexing

In [29]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print('array2d:\n', array2d)

array3 = array2d[[0,1], 2]
print('array3:\n', array3)
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array3:
 [3 6]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


* Boolean indexing

In [32]:
array1d = np.arange(start=1, stop=10)
print('array1d:', array1d > 5)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d: [False False False False False  True  True  True  True]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [33]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [34]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [36]:
indexes = np.array([5,6,7,8])
print(indexes)
print('array1d:', array1d)
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

[5 6 7 8]
array1d: [1 2 3 4 5 6 7 8 9]
일반 인덱스로 필터링 결과 : [6 7 8 9]


# NumPy의 np와 ndarray 차이점

NumPy에서 `np`는 NumPy 라이브러리 자체를 의미하고, `ndarray`는 NumPy의 핵심 데이터 구조인 다차원 배열 객체를 의미합니다.

## 예시 파일

````python
import numpy as np

print("=== np와 ndarray의 차이점 완벽 이해하기 ===\n")

# 1. np는 NumPy 라이브러리 자체
print("1. np는 NumPy 라이브러리:")
print(f"   np의 타입: {type(np)}")
print(f"   np는 모듈입니다: {np}")
print()

# 2. ndarray는 NumPy의 데이터 구조
arr = np.array([1, 2, 3, 4, 5])
print("2. ndarray는 NumPy의 데이터 구조:")
print(f"   배열: {arr}")
print(f"   배열의 타입: {type(arr)}")
print(f"   정확한 클래스명: {arr.__class__}")
print()

# 3. np를 통한 함수 호출 vs ndarray 메서드
print("3. np 함수 vs ndarray 메서드 비교:")
original_array = np.array([3, 1, 9, 5])
print(f"   원본 배열: {original_array}")

# np.sort() - 함수 방식 (원본 유지)
sorted_by_np = np.sort(original_array)
print(f"   np.sort() 결과: {sorted_by_np}")
print(f"   원본 배열 상태: {original_array}")

# ndarray.sort() - 메서드 방식 (원본 변경)
copy_array = original_array.copy()
result = copy_array.sort()
print(f"   ndarray.sort() 결과: {result}")
print(f"   원본 배열 상태: {copy_array}")
print()

# 4. np를 통해 접근할 수 있는 것들
print("4. np를 통해 접근할 수 있는 것들:")
print("   - 배열 생성 함수들:")
print(f"     np.array(): {type(np.array)}")
print(f"     np.zeros(): {type(np.zeros)}")
print(f"     np.ones(): {type(np.ones)}")
print(f"     np.arange(): {type(np.arange)}")

print("   - 수학 함수들:")
print(f"     np.sin(): {type(np.sin)}")
print(f"     np.cos(): {type(np.cos)}")
print(f"     np.sum(): {type(np.sum)}")

print("   - 상수들:")
print(f"     np.pi: {np.pi}")
print(f"     np.e: {np.e}")
print()

# 5. ndarray 객체가 가진 속성과 메서드들
print("5. ndarray 객체의 속성과 메서드들:")
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
print(f"   배열: \n{sample_array}")
print(f"   속성들:")
print(f"     .shape: {sample_array.shape}")
print(f"     .dtype: {sample_array.dtype}")
print(f"     .ndim: {sample_array.ndim}")
print(f"     .size: {sample_array.size}")
print()

print(f"   메서드들:")
print(f"     .reshape(): {type(sample_array.reshape)}")
print(f"     .flatten(): {type(sample_array.flatten)}")
print(f"     .sum(): {type(sample_array.sum)}")
print(f"     .mean(): {type(sample_array.mean)}")
print()

# 6. 실제 사용 예시 비교
print("6. 실제 사용 예시 비교:")
data = np.array([1, 2, 3, 4, 5])

# np를 통한 함수 호출
print("   np를 통한 함수 호출:")
print(f"     np.sum(data): {np.sum(data)}")
print(f"     np.mean(data): {np.mean(data)}")
print(f"     np.max(data): {np.max(data)}")

# ndarray 메서드 호출
print("   ndarray 메서드 호출:")
print(f"     data.sum(): {data.sum()}")
print(f"     data.mean(): {data.mean()}")
print(f"     data.max(): {data.max()}")
print()

# 7. 정렬 함수의 차이점 상세 분석
print("7. 정렬 함수의 차이점 상세 분석:")
test_array = np.array([5, 2, 8, 1, 9])
print(f"   테스트 배열: {test_array}")

# np.sort() - 새로운 배열 반환
sorted_new = np.sort(test_array)
print(f"   np.sort() 후:")
print(f"     반환값: {sorted_new}")
print(f"     원본 배열: {test_array}")

# ndarray.sort() - 원본 배열 수정
test_array_copy = test_array.copy()
return_value = test_array_copy.sort()
print(f"   ndarray.sort() 후:")
print(f"     반환값: {return_value}")
print(f"     원본 배열: {test_array_copy}")
print()

# 8. 메모리 관점에서의 차이
print("8. 메모리 관점에서의 차이:")
large_array = np.random.randint(0, 100, size=1000000)
print(f"   대용량 배열 크기: {large_array.size} 개 원소")

# np.sort()는 새로운 메모리 할당
import time
start_time = time.time()
sorted_copy = np.sort(large_array)
np_sort_time = time.time() - start_time
print(f"   np.sort() 시간: {np_sort_time:.4f}초 (새 배열 생성)")

# ndarray.sort()는 기존 메모리 사용
large_array_copy = large_array.copy()
start_time = time.time()
large_array_copy.sort()
ndarray_sort_time = time.time() - start_time
print(f"   ndarray.sort() 시간: {ndarray_sort_time:.4f}초 (기존 배열 수정)")
print()

print("=== 핵심 정리 ===")
print("• np: NumPy 라이브러리 모듈")
print("  - 함수들과 상수들을 제공")
print("  - 배열을 생성하고 조작하는 도구")
print("• ndarray: NumPy의 다차원 배열 객체")
print("  - 실제 데이터를 담는 컨테이너")
print("  - 자체적인 메서드와 속성을 가짐")
print("• np.sort(): 새로운 정렬된 배열 반환 (원본 유지)")
print("• ndarray.sort(): 원본 배열을 직접 정렬 (메모리 효율적)")
````

## 답변

### 핵심 차이점

**np (NumPy 라이브러리)**
- NumPy 라이브러리 자체를 의미하는 모듈
- 배열 생성, 수학 함수, 상수 등을 제공하는 도구상자
- `import numpy as np`로 가져와서 사용

**ndarray (N-dimensional Array)**
- NumPy의 핵심 데이터 구조인 다차원 배열 객체
- 실제 데이터를 저장하고 관리하는 컨테이너
- `np.array()`를 통해 생성되는 객체의 타입

### 정렬 함수의 중요한 차이점

````python
# 새로운 셀에 추가

import numpy as np

# 원본 배열
original = np.array([3, 1, 9, 5])
print(f"원본 배열: {original}")

# 1. np.sort() - 함수 방식
sorted_copy = np.sort(original)
print(f"np.sort() 결과: {sorted_copy}")
print(f"원본 배열 상태: {original}")  # 변경되지 않음

# 2. ndarray.sort() - 메서드 방식
original_copy = original.copy()
return_value = original_copy.sort()
print(f"ndarray.sort() 반환값: {return_value}")  # None
print(f"원본 배열 상태: {original_copy}")  # 변경됨
````

### 사용 패턴 비교

| 구분 | np | ndarray |
|------|-----|---------|
| **정체성** | 라이브러리 모듈 | 데이터 객체 |
| **생성** | `import numpy as np` | `np.array([1,2,3])` |
| **함수 호출** | `np.sort(array)` | `array.sort()` |
| **반환값** | 새로운 배열 | 원본 수정 또는 None |
| **메모리** | 추가 메모리 사용 | 기존 메모리 활용 |

### 언제 어떤 것을 사용할까?

**np.sort() 사용 시기:**
- 원본 데이터를 보존해야 할 때
- 정렬된 새로운 배열이 필요할 때
- 함수형 프로그래밍 스타일을 선호할 때

**ndarray.sort() 사용 시기:**
- 메모리를 절약해야 할 때
- 원본 데이터 수정이 허용될 때
- 대용량 데이터 처리 시

### 추가 자료
- [NumPy 공식 문서 - ndarray](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)
- [NumPy 정렬 함수 가이드](https://numpy.org/doc/stable/reference/routines.sort.html)
- [NumPy 메모리 레이아웃 이해하기](https://numpy.org/doc/stable/user/basics.indexing.html#memory-layout)

### 행렬의 정렬 – sort( )와 argsort( )

* 행렬 정렬

In [37]:
org_array = np.array([ 3, 1, 9, 5]) 
print('원본 행렬:', org_array)
# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)         
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1) 
print('np.sort( ) 호출 후 원본 행렬:', org_array)
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)


원본 행렬: [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [38]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


NumPy 배열 슬라이싱에서 :: 사용법
NumPy 배열에서 [::-1]과 같은 슬라이싱 문법은 배열의 순서를 역순으로 만드는 강력한 기능입니다.

예시 파일

In [39]:
import numpy as np

print("=== NumPy 슬라이싱 :: 문법 완벽 이해하기 ===\n")

# 1. 기본 슬라이싱 문법 [start:stop:step]
original_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("원본 배열:", original_array)

# 기본 슬라이싱 예제들
print("\n=== 기본 슬라이싱 예제 ===")
print("전체 배열 [:]:", original_array[:])
print("처음부터 5까지 [:5]:", original_array[:5])
print("3부터 끝까지 [3:]:", original_array[3:])
print("2부터 8까지 [2:8]:", original_array[2:8])

# 2. step 파라미터 사용
print("\n=== step 파라미터 사용 ===")
print("2칸씩 건너뛰기 [::2]:", original_array[::2])
print("3칸씩 건너뛰기 [::3]:", original_array[::3])
print("처음부터 8까지 2칸씩 [:8:2]:", original_array[:8:2])

# 3. 역순 슬라이싱
print("\n=== 역순 슬라이싱 ===")
print("전체 역순 [::-1]:", original_array[::-1])
print("2칸씩 역순 [::-2]:", original_array[::-2])
print("끝에서 3번째부터 역순 [-3::-1]:", original_array[-3::-1])

# 4. 정렬과 역순의 실제 사용 예
print("\n=== 정렬과 역순 활용 ===")
unsorted_array = np.array([3, 1, 9, 5, 2, 8, 4])
print("정렬 전 배열:", unsorted_array)

# 오름차순 정렬
sorted_asc = np.sort(unsorted_array)
print("오름차순 정렬:", sorted_asc)

# 내림차순 정렬 (정렬 후 역순)
sorted_desc = np.sort(unsorted_array)[::-1]
print("내림차순 정렬:", sorted_desc)

# 5. 2차원 배열에서의 슬라이싱
print("\n=== 2차원 배열 슬라이싱 ===")
array_2d = np.array([[1, 2, 3, 4],
                     [5, 6, 7, 8],
                     [9, 10, 11, 12]])
print("원본 2차원 배열:")
print(array_2d)

print("\n행 순서 역순 [::-1]:")
print(array_2d[::-1])

print("\n열 순서 역순 [:, ::-1]:")
print(array_2d[:, ::-1])

print("\n행과 열 모두 역순 [::-1, ::-1]:")
print(array_2d[::-1, ::-1])

# 6. 실제 데이터 처리 예제
print("\n=== 실제 데이터 처리 예제 ===")
student_scores = np.array([85, 92, 78, 96, 88, 73, 91])
student_names = np.array(['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace'])

print("학생 이름:", student_names)
print("학생 점수:", student_scores)

# 점수 순으로 정렬 (높은 순)
sorted_indices = np.argsort(student_scores)[::-1]
print("\n성적 높은 순으로 정렬된 인덱스:", sorted_indices)
print("성적 순 학생 이름:", student_names[sorted_indices])
print("성적 순 점수:", student_scores[sorted_indices])

# 7. 다양한 step 값 실험
print("\n=== 다양한 step 값 실험 ===")
test_array = np.arange(20)
print("테스트 배열:", test_array)
print("step=1 (기본):", test_array[::1])
print("step=2:", test_array[::2])
print("step=3:", test_array[::3])
print("step=-1 (역순):", test_array[::-1])
print("step=-2 (2칸씩 역순):", test_array[::-2])

# 8. 부분 구간 역순
print("\n=== 부분 구간 역순 ===")
numbers = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("원본:", numbers)
print("3~7 구간만 역순 [3:8][::-1]:", numbers[3:8][::-1])
print("처음 5개만 역순 [:5][::-1]:", numbers[:5][::-1])
print("마지막 5개만 역순 [-5:][::-1]:", numbers[-5:][::-1])

print("\n=== 핵심 정리 ===")
print("• [start:stop:step] - 슬라이싱의 기본 문법")
print("• [::-1] - 전체 배열을 역순으로")
print("• [::2] - 2칸씩 건너뛰며 선택")
print("• [::-2] - 2칸씩 건너뛰며 역순으로")
print("• 정렬 후 [::-1]로 내림차순 만들기")
print("• 2차원에서는 각 축별로 독립적으로 적용 가능")

=== NumPy 슬라이싱 :: 문법 완벽 이해하기 ===

원본 배열: [ 1  2  3  4  5  6  7  8  9 10]

=== 기본 슬라이싱 예제 ===
전체 배열 [:]: [ 1  2  3  4  5  6  7  8  9 10]
처음부터 5까지 [:5]: [1 2 3 4 5]
3부터 끝까지 [3:]: [ 4  5  6  7  8  9 10]
2부터 8까지 [2:8]: [3 4 5 6 7 8]

=== step 파라미터 사용 ===
2칸씩 건너뛰기 [::2]: [1 3 5 7 9]
3칸씩 건너뛰기 [::3]: [ 1  4  7 10]
처음부터 8까지 2칸씩 [:8:2]: [1 3 5 7]

=== 역순 슬라이싱 ===
전체 역순 [::-1]: [10  9  8  7  6  5  4  3  2  1]
2칸씩 역순 [::-2]: [10  8  6  4  2]
끝에서 3번째부터 역순 [-3::-1]: [8 7 6 5 4 3 2 1]

=== 정렬과 역순 활용 ===
정렬 전 배열: [3 1 9 5 2 8 4]
오름차순 정렬: [1 2 3 4 5 8 9]
내림차순 정렬: [9 8 5 4 3 2 1]

=== 2차원 배열 슬라이싱 ===
원본 2차원 배열:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

행 순서 역순 [::-1]:
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]

열 순서 역순 [:, ::-1]:
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]

행과 열 모두 역순 [::-1, ::-1]:
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]

=== 실제 데이터 처리 예제 ===
학생 이름: ['Alice' 'Bob' 'Charlie' 'David' 'Eve' 'Frank' 'Grace']
학생 점수: [85 92 78 96 88 73 91]

성적 높은 순으로 정렬된 인덱스: [3 1 6 4 0 2 5]


슬라이싱 문법의 기본 구조
NumPy 배열의 슬라이싱은 [start:stop:step] 형태로 작동합니다:

start: 시작 인덱스 (생략 시 처음부터)
stop: 끝 인덱스 (생략 시 끝까지)
step: 간격 (생략 시 1, 음수면 역순)
[::-1]의 의미

In [40]:
# 새로운 셀에 추가

import numpy as np

# 기본 예제
org_array = np.array([3, 1, 9, 5])
print("원본 배열:", org_array)

# 정렬 후 역순으로 만들기
sorted_asc = np.sort(org_array)
print("오름차순 정렬:", sorted_asc)

sorted_desc = np.sort(org_array)[::-1]
print("내림차순 정렬:", sorted_desc)

# [::-1] 분해 설명
print("\n=== [::-1] 분해 설명 ===")
print("[::-1]는 다음과 같은 의미:")
print("  start: 생략 (끝에서 시작)")
print("  stop: 생략 (처음까지)")
print("  step: -1 (한 칸씩 뒤로)")

# 추가 예제 셀
data = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("원본:", data)

print("\n=== 다양한 패턴 ===")
print("[::1]  (기본):", data[::1])
print("[::2]  (2칸씩):", data[::2])
print("[::3]  (3칸씩):", data[::3])
print("[::-1] (역순):", data[::-1])
print("[::-2] (2칸씩 역순):", data[::-2])
print("[2:8:2] (2~7 중 2칸씩):", data[2:8:2])
print("[7:1:-1] (7~2까지 역순):", data[7:1:-1])

# 2차원 배열 예제
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6], 
                     [7, 8, 9]])
print("원본 2차원 배열:")
print(array_2d)

print("\n행 순서 역순 [::-1]:")
print(array_2d[::-1])

print("\n열 순서 역순 [:, ::-1]:")
print(array_2d[:, ::-1])

print("\n행과 열 모두 역순 [::-1, ::-1]:")
print(array_2d[::-1, ::-1])

원본 배열: [3 1 9 5]
오름차순 정렬: [1 3 5 9]
내림차순 정렬: [9 5 3 1]

=== [::-1] 분해 설명 ===
[::-1]는 다음과 같은 의미:
  start: 생략 (끝에서 시작)
  stop: 생략 (처음까지)
  step: -1 (한 칸씩 뒤로)
원본: [0 1 2 3 4 5 6 7 8 9]

=== 다양한 패턴 ===
[::1]  (기본): [0 1 2 3 4 5 6 7 8 9]
[::2]  (2칸씩): [0 2 4 6 8]
[::3]  (3칸씩): [0 3 6 9]
[::-1] (역순): [9 8 7 6 5 4 3 2 1 0]
[::-2] (2칸씩 역순): [9 7 5 3 1]
[2:8:2] (2~7 중 2칸씩): [2 4 6]
[7:1:-1] (7~2까지 역순): [7 6 5 4 3 2]
원본 2차원 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

행 순서 역순 [::-1]:
[[7 8 9]
 [4 5 6]
 [1 2 3]]

열 순서 역순 [:, ::-1]:
[[3 2 1]
 [6 5 4]
 [9 8 7]]

행과 열 모두 역순 [::-1, ::-1]:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


# 실제 사용 사례  

내림차순 정렬: np.sort(array)[::-1]  
배열 뒤집기: array[::-1]  
부분 역순: array[2:8][::-1]  
건너뛰며 선택: array[::2]  
거꾸로 건너뛰기: array[::-2]  

# 성능 고려사항  

[::-1]은 새로운 배열을 생성하지 않고 뷰(view)를 반환  
메모리 효율적이며 빠른 연산  
원본 데이터는 변경되지 않음  
추가 자료  
 

In [42]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

print('원본 행렬:\n', np.sort(array2d))

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]
원본 행렬:
 [[ 8 12]
 [ 1  7]]


* 정렬 행렬의 인덱스 반환

In [43]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [44]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [46]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])
print('성적 오름차순으로 score_array의 성적 출력:', score_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
성적 오름차순으로 score_array의 성적 출력: [78 84 88 95 98]


### 선형대수 연산 – 행렬 내적과 전치 행렬 구하기

* 행렬 내적

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

* 전치 행렬

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)