<a href="https://colab.research.google.com/github/hundong2/machine_learning/blob/master/20230822/Sort_argsort.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [3]:
org_array = np.array([3,1,9,5])
print(org_array)

# np.sort()
sort_array1 = np.sort(org_array)
print('sort : ', sort_array1)

# ndarray.sort()
sort_array2 = org_array.sort()
print('sort array : ', sort_array2 )
print('sort array origin : ', org_array)

[3 1 9 5]
sort :  [1 3 5 9]
sort array :  None
sort array origin :  [1 3 5 9]


In [4]:
sort_array1_desc = np.sort(org_array)[::-1]
print(sort_array1_desc)

[9 5 3 1]


In [6]:
array2d = np.array([[8, 12], [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis=0) # row
sort_array2d_axis1 = np.sort(array2d, axis=1) # col


print(sort_array2d_axis0)
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


# 정렬 된 행렬의 인덱스를 반환하기

np.argsort() 는 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.


In [9]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(' index array ', sort_indices)

<class 'numpy.ndarray'>
 index array  [1 0 3 2]


# ndarray 에 array 배열을 index를 넣으면 index 순으로 정렬이 된다.

In [11]:
name_array = np.array(['A', 'B', 'C', 'D', 'E'])
score_array = np.array([70, 99, 83, 97, 89])

sort_indices_asc = np.argsort(score_array)
print('sort indices asc ', sort_indices_asc)
print('score asc : ', name_array[sort_indices_asc])

sort indices asc  [0 2 4 3 1]
score asc :  ['A' 'C' 'E' 'D' 'B']
