<a href="https://colab.research.google.com/github/hundong2/machine_learning/blob/master/20230815/IndexingOfNdarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# data indexing of numpy ndarray
1. 특정한 데이터만 추출
  - 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터 반환
2. 슬라이싱( Slicing )
  - 연속된 인덱스 상의 ndarray를 추출하는 방식 `:` 기호 사이에 시작 인덱스와 종료 인덱스 ( `시작 index` ~ `종료 인덱스 - 1 ` ) 데이터를 반환
3. 팬시 인덱싱 ( fancy indexing )
  - 일정한 인덱싱 집합을 list or ndarray 형태로 지정, 해당 위치 데이터의 ndarray를 반환
4. 불린 인덱싱 ( boolean indexing )
  - 특정 조건에 해당하는지 true/false 값 인덱싱 집합을 기반으로 ture에 해당하는 인덱스 위치에 데이터( darray )를 반환

## 1. 특정한 데이터만 추출 ( 배열 )

In [ ]:
import numpy as np
# 1 ~ 9 1 dimension ndarray
array1 = np.arange(start=1, stop=10) # array1 = np.arange(1, 10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))
print(' 맨 뒤의 값:', array1[-1], '맨 뒤의 세번째 값', array1[-3])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
 맨 뒤의 값: 9 맨 뒤의 세번째 값 7


In [ ]:
# 값 변경
array1[0] = 9
array1[8] = 0
print('diff array:', array1)

diff array: [9 2 3 4 5 6 7 8 0]


- darray에 배열에 접근하는 방식은 일반 프로그래밍언어의 array접근 방식과 같다

In [ ]:
array3d = array1.reshape(-1,3)
print('array3d:\n', array3d)

array3d:
 [[9 2 3]
 [4 5 6]
 [7 8 0]]


In [ ]:
print('row 0, col 1 :', array3d[0][1])
print('row 1, col 2 :' , array3d[1][2])
print('row2, col 0 :', array3d[2][0])

row 0, col 1 : 2
row 1, col 2 : 6
row2, col 0 : 7


## Slicing ( 슬라이싱 )
- 특정 열 잘라서 가져오기

In [ ]:
# 1차원
array1 = np.arange(start=1, stop=10)
array4 = array1[:3] # 0 부터 3개
print(array4)

array5 = array1[3:] #0,1,2 /(자르고)  3 부터 끝까지
print(array5)

array6 = array1[:] # 0 부터 끝까지
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print(array2d[0:1, 0:3])

print(array2d[0], ' shape : ' , array2d[0].shape)
print(array2d[1], ' shape : ' , array2d[1].shape)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]]
[1 2 3]  shape :  (3,)
[4 5 6]  shape :  (3,)


# 팬시 인덱싱 ( fancy indexing )
- list나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환


In [ ]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print(array2d)
print(array3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6]


# 불린 인덱싱 ( boolean indexing )

- 조건은 필터링과 검색을 동시에 할 수 있다.
- 1차원 ndarray 에서 [1,2,3,4,5,6,7,8,9] -> 5보다 큰값을 추출하는 방법

## c#

list = [1,2,3,4,5,6,7,8,9]

list.where(x => x > 5 ).toList()

In [15]:
array1d = np.arange(start=1, stop=10)
# [] array1d > 5 boolean indexing
array3 = array1d[array1d > 5]
print('result : ', array3)

result :  [6 7 8 9]


In [16]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [17]:
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
array4 = array1d[boolean_indexes]
print(array4)

[6 7 8 9]
