<a href="https://colab.research.google.com/github/hundong2/machine_learning/blob/master/20230815/ndarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array study

In [2]:
import numpy as np

# Dimension - 차원

array1 = np.array([1,2,3])
array2 = np.array([[1,2,3,], [4,5,6]])
array3 = np.array([[1,2,3]])

print( 'array1 type : ', type(array1))
print( 'array1 array shape : ', array1.shape)
print( 'array2 type : ', type(array2))
print( 'array2 array shape : ', array2.shape)
print( 'array3 type : ', type(array3))
print( 'array3 array shape : ', array3.shape)

print( 'dimension')
print( 'array1 : {:0} dim, array2 : {:1} dim, array3 : {:2} dim'.format(array1.ndim, array2.ndim, array3.ndim))


array1 type :  <class 'numpy.ndarray'>
array1 array shape :  (3,)
array2 type :  <class 'numpy.ndarray'>
array2 array shape :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 array shape :  (1, 3)
dimension
array1 : 1 dim, array2 : 2 dim, array3 :  2 dim


# ndarray data type

## integer, string, bool ... complex
- The data type in ndarray can only be of the same data type due to the nature of the operation.  
- Int and float cannot exist together in one ndarray object.  


In [3]:
# ndarray type
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [4]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)
# U21 -> Unicode
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


# ndarray change data type

`astype()`  
- 메모리를 절약하기 위해 사용 될 수 있다.


In [5]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


# ndarray - arange, zeros, ones
- ndarray 연속 값 or 0,1 초기화
- 테스트용으로 테스트 데이터 생성 or 대규모의 데이터를 일괄적으로 초기화 할 떄 사용

In [8]:
sequence_array = np.arange(10) # 0~ 9 ( 10 - 1 )
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


## zeros
- zeros 는 tuple 형태의 인자값 입력 시 0으로 채운 shape를 가진 ndarray를 출력
- default type = float64

In [11]:
zero_array = np.zeros((3,2), dtype='int32') # default type float64
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


# reshape()
- 차원과 크기를 변경
- parameter dimension 정보 ( row , column )


In [14]:
array1 = np.arange(10)
print('array1:\n', array1)
array2 = array1.reshape(2, 5)
print('array2:\n', array2)
array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
array1.reshape(4,3) # error (10, ) -> (4, 3) 변경 불가

ValueError: ignored

# reshape
- 인자로 -1을 입력하는 경우 새로운 shape로 변환

In [16]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5)
array3 = array1.reshape(5, -1)
print('array2: \n{:0}', array2.shape)
print('array3: \n{:0}', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2: 
{:0} (2, 5)
array3: 
{:0} (5, 2)


In [17]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4) # error

ValueError: ignored

# 자료형 변환
- tolist() method
- darray -> list

In [18]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

# 3 dimension to 2 dim ndarray change
array5 = array3d.reshape(-1, 1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

# change 1 dim ndarray to 2 dim ndarray
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
