# 파이토치

In [7]:
import torch

# 쉽게 이해 가능한 코드 형태.
# 텐서를 생성합니다. 이 텐서는 [1, 2, 3]의 값을 가집니다.

tensor = torch.tensor([1, 2, 3]) 
print(tensor)

tensor([1, 2, 3])


In [8]:
#빠른 프로토 타이핑 

# 간결한 딥러닝 모델 구조 정의
model = torch.nn.Sequential( 
    torch.nn.Linear(10, 5),
    torch.nn.ReLU(),         
    torch.nn.Linear(5, 2)    
)

In [9]:
#강력한 GPU지원 
# GPU 사용
if torch.cuda.is_available():  # CUDA를 사용 가능한지 확인
    tensor = tensor.to('cuda') # CUDA를 사용하기
else:
    tensor = tensor.to('cpu')  # CPU를 사용하기
    print("CUDA를 사용할 수 없습니다. CPU를 사용합니다.")

CUDA를 사용할 수 없습니다. CPU를 사용합니다.


In [10]:
# MAC OS 

import torch
print(torch.__version__)
print("MPS available:", torch.backends.mps.is_available())
print("MPS built:", torch.backends.mps.is_built())

import torch

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

x = torch.randn(3, 3).to(device)
model = torch.nn.Linear(3, 1).to(device)

y = model(x)
print("device:", device)
print(y)



2.12.1
MPS available: True
MPS built: True
device: mps
tensor([[ 0.2823],
        [ 0.0151],
        [-0.5092]], device='mps:0', grad_fn=<LinearBackward0>)


In [11]:
import sys
from wrapper import get_device, to_device

device = get_device()
print(f"Using device: {device}")

Using device: mps


# 동적 계산 그래프(Dynamic Computation Graph)



In [12]:
# 자동 미분
x = torch.tensor(1., requires_grad=True)
y = x * 2
y.backward()   # 미분 계산
print(x.grad)  # x에 대한 y의 미분 값 확인

tensor(2.)


## 풍부한 라이브러리 및 커뮤니티 

```python
import torchvision #이미지 처리용 라이브러리 
import torchtext #텍스트 처리용 라이브러리
import torchaudio #오디오 데이터 처리용 라이브러리
```

In [13]:
# 사용자 정의 신경망 레이어
class CustomLayer(torch.nn.Module):
    def __init__(self):
        super(CustomLayer, self).__init__()
        # 레이어 초기화

    def forward(self, x):
        # 데이터 x에 대한 연산
        return x

# 모델에 사용자 정의 레이어 적용
model.add_module('custom_layer', CustomLayer())

## 4. pytorch 와 tensorflow비교



In [14]:
import torch

# 텐서 생성
a = torch.tensor([2., 3.])
b = torch.tensor([6., 4.])

# 텐서 덧셈 연산
c = torch.add(a, b)

print(c)

tensor([8., 7.])


In [16]:
import tensorflow as tf

# 텐서 생성
a = tf.constant([2., 3.])
b = tf.constant([6., 4.])

# 텐서 덧셈 연산
c = tf.add(a, b)

print(c)

tf.Tensor([8. 7.], shape=(2,), dtype=float32)


# 5. 파이토치 핵심 모듈 소개 

```python
import torch
import torch.nn as nn #딥러닝 모델 구축 , 신경망을 구성하는데 필요한 다양한 도구들이 포함 
from torch.utils.data import data #데이터 전처리, 데이터 로딩
import torch.optim as optim #최적화 알고리즘 
import torch.autograd as autograd #자동 미분
import torch.cuda as cuda #gpu사용 
```