# 텐서(tensor)의 개념과 텐서 생성 

In [1]:
# 1.1 리스트 데이터로 텐서 생성하기 

import torch

ls = [1, 2, 3, 4, 5]
tensor1 = torch.tensor(ls)

print(tensor1)

tensor([1, 2, 3, 4, 5])


In [2]:
# 넘파이 배열로 텐서 생성 
import numpy as np

numpy_array = np.array([1.5, 2.5, 3.5])
tensor2 = torch.tensor(numpy_array)

print(tensor2)

tensor([1.5000, 2.5000, 3.5000], dtype=torch.float64)


In [ ]:
# 정수형 텐서 생성
int_tensor = torch.tensor([1,2,3,4])

print("정수형 텐서 값: ", int_tensor)
print("텐서의 타입: ", int_tensor.dtype)

# 부동 소수점형 텐서 생성
float_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])

print("실수형 텐서 값: ", float_tensor)
print("텐서의 타입: ", float_tensor.dtype)

bool_tensor = torch.tensor([True, False, True])

print("불리언 텐서 값: ", bool_tensor)
print("텐서의 타입: ", bool_tensor.dtype)



정수형 텐서 값:  tensor([1, 2, 3, 4])
텐서의 타입:  torch.int64
실수형 텐서 값:  tensor([1., 2., 3., 4.])
텐서의 타입:  torch.float32
불리언 텐서 값:  tensor([ True, False,  True])
텐서의 타입:  torch.bool


Compacted conversation# PyTorch 데이터 타입 (Tensor Dtypes)

## 정수형 (Integer Types)

| 타입 | 문자표기 | 비트 | 범위 | 설명 |
|------|---------|------|------|------|
| `torch.int8` | i8 | 8 | -128 ~ 127 | 부호있는 8비트 정수 |
| `torch.int16` | i16 | 16 | -32,768 ~ 32,767 | 부호있는 16비트 정수 |
| `torch.int32` | i32 | 32 | -2^31 ~ 2^31-1 | 부호있는 32비트 정수 |
| `torch.int64` | i64 | 64 | -2^63 ~ 2^63-1 | 부호있는 64비트 정수 (기본값) |
| `torch.uint8` | u8 | 8 | 0 ~ 255 | 부호없는 8비트 정수 |

## 부동소수점형 (Floating Point Types)

| 타입 | 문자표기 | 비트 | 정밀도 | 설명 |
|------|---------|------|--------|------|
| `torch.float16` | f16 | 16 | ~3.3자리 | 반정밀도 (GPU 연산 가속) |
| `torch.bfloat16` or `torch.half` | bf16 | 16 | ~3.3자리 | Brain 반정밀도 |
| `torch.float32` or `torch.float` | f32 | 32 | ~7자리 | 단정밀도 (기본값) |
| `torch.float64` or `torch.double` | f64 | 64 | ~15자리 | 배정밀도 (double) |

## 복소수형 (Complex Types)

| 타입 | 문자표기 | 메모리 | 설명 |
|------|---------|--------|------|
| `torch.complex64` | c64 | 64 | 실부/허부 float32 |
| `torch.complex128` or `torch.cdouble` | c128 | 128 | 실부/허부 float64 |

## 기타 타입 (Others)

| 타입 | 문자표기 | 설명 |
|------|---------|------|
| `torch.bool` | b8 | 부울 타입 (True/False) |
| `torch.qint8` | qi8 | 양자화 8비트 정수 |
| `torch.qint32` | qi32 | 양자화 32비트 정수 |
| `torch.quint8` | qu8 | 부호없는 양자화 8비트 |

In [7]:
#지정된 데이터 타입으로 텐서 생성 
specified_float_tensor = torch.tensor([1, 2, 3, 4], dtype=torch.float32)

print("타입 변환한 텐서 값: ", specified_float_tensor)
print("텐서의 타입: ", specified_float_tensor.dtype)

타입 변환한 텐서 값:  tensor([1., 2., 3., 4.])
텐서의 타입:  torch.float32


In [13]:
#tensor의 타입 변경 
# 초기 텐서 생성 (정수 타입)
tensor = torch.tensor([1, 2, 3, 4])

print("1. 텐서의 타입 변경 function\n")
# 텐서 속성 변환
float_tensor = tensor.float() # int -> float
int_tensor = float_tensor.int() # float -> int
double_tensor = float_tensor.double() # float -> double
bool_tensor = int_tensor.bool() # int -> bool

print("처음 생성한 텐서:", tensor.dtype)
print('float_tensor의 타입 확인: ', float_tensor.dtype)
print('int_tensor의 타입 확인: ', int_tensor.dtype)
print('double_tensor의 타입 확인: ', double_tensor.dtype)
print('bool_tensor의 타입 확인: ', bool_tensor.dtype)

print("\n2. 텐서의 타입 변경 to method\n")
#텐서의 타입 변경 to method 
# 텐서 속성 변환
float_tensor2 = tensor.to(dtype=torch.float32)
int_tensor2 = float_tensor.to(dtype=torch.int32)
double_tensor2 = float_tensor.to(dtype=torch.float64)
bool_tensor2 = int_tensor.to(dtype=torch.bool)

print("처음 생성한 텐서:", tensor.dtype)
print('float_tensor의 타입 확인: ', float_tensor2.dtype)
print('int_tensor의 타입 확인: ', int_tensor2.dtype)
print('double_tensor의 타입 확인: ', double_tensor2.dtype)
print('bool_tensor의 타입 확인: ', bool_tensor2.dtype)

1. 텐서의 타입 변경 function

처음 생성한 텐서: torch.int64
float_tensor의 타입 확인:  torch.float32
int_tensor의 타입 확인:  torch.int32
double_tensor의 타입 확인:  torch.float64
bool_tensor의 타입 확인:  torch.bool

2. 텐서의 타입 변경 to method

처음 생성한 텐서: torch.int64
float_tensor의 타입 확인:  torch.float32
int_tensor의 타입 확인:  torch.int32
double_tensor의 타입 확인:  torch.float64
bool_tensor의 타입 확인:  torch.bool


# 3. 차원(Dimension)과 형태(Shape)

- 0차원 텐서: 스칼라(단일 숫자)
- 1차원 텐서: 벡터(숫자의 배열)
- 2차원 텐서: 행렬(숫자의 2차원 배열)
- 3차원 텐서: 다차원 배열을 의미

In [17]:
data = 5

scalar = torch.tensor(data)

print("스칼라: ", scalar)
print("스칼라 차원: ", scalar.dim())
print("스칼라 형태: ", scalar.shape)

data = [1, 2, 3]

vector = torch.tensor(data)

print("벡터: ", vector)
print("벡터 차원:", vector.dim())
print("벡터 형태:", vector.shape)

data = [[1, 2, 3],
        [4, 5, 6]]

matrix = torch.tensor(data)

print("행렬: ", matrix)
print("행렬 차원: ", matrix.dim())
print("행렬 형태: ", matrix.shape)

data = [
    [[1, 2, 3],
     [3, 4, 5]],
    [[5, 6, 7],
     [7, 8, 8]]
]
tensor3D = torch.tensor(data)

print("3차원 텐서", tensor3D)
print("3차원 텐서 차원:", tensor3D.dim())
print("3차원 텐서 형태:", tensor3D.shape)

스칼라:  tensor(5)
스칼라 차원:  0
스칼라 형태:  torch.Size([])
벡터:  tensor([1, 2, 3])
벡터 차원: 1
벡터 형태: torch.Size([3])
행렬:  tensor([[1, 2, 3],
        [4, 5, 6]])
행렬 차원:  2
행렬 형태:  torch.Size([2, 3])
3차원 텐서 tensor([[[1, 2, 3],
         [3, 4, 5]],

        [[5, 6, 7],
         [7, 8, 8]]])
3차원 텐서 차원: 3
3차원 텐서 형태: torch.Size([2, 2, 3])


In [33]:
#zeros
zeros_tensor = torch.zeros(2, 3)
print("영(0) 텐서:\n", zeros_tensor)

ones_tensor = torch.ones(2, 3)
print("일(1) 텐서:\n", ones_tensor)

full_tensor = torch.full((2, 3), 5)
print("Full 텐서:\n", full_tensor)

eye_tensor = torch.eye(3) # 3x3 단위 행렬 생성
print("\nIdentity Matrix (Eye Tensor):\n", eye_tensor)

arange_tensor = torch.arange(0, 10, 2) # 0부터 10 미만까지 2씩 증가
print("\nArange Tensor:\n", arange_tensor)

linspace_tensor = torch.linspace(0, 10, 5) # 0부터 10까지 5개의 요소를 균등하게 배치
print("\nLinspace Tensor:\n", linspace_tensor)

rand_tensor = torch.rand(2, 3)
print("\n균일 분포 랜덤 텐서 (torch.rand):\n", rand_tensor)

randn_tensor = torch.randn(2, 3)
print("\n정규 분포 랜덤 텐서 (torch.randn):\n", randn_tensor)
#주어진 크기의 텐서를 생성하고, 모든 요소를 평균 0, 표준편차 1을 갖는 정규 분포에서 샘플링된 값으로 초기화합니다.

randint_tensor = torch.randint(low=0, high=10, size=(2, 3))
print("\n정수 랜덤 텐서(torch.randint) :\n", randint_tensor)

randperm_tensor = torch.randperm(10) # 0부터 9까지의 숫자를 랜덤하게 섞음
print("\n랜덤 순열(Permutation) 텐서:\n", randperm_tensor)


영(0) 텐서:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
일(1) 텐서:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Full 텐서:
 tensor([[5, 5, 5],
        [5, 5, 5]])

Identity Matrix (Eye Tensor):
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

Arange Tensor:
 tensor([0, 2, 4, 6, 8])

Linspace Tensor:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

균일 분포 랜덤 텐서 (torch.rand):
 tensor([[0.4641, 0.9801, 0.4273],
        [0.6049, 0.4391, 0.5341]])

정규 분포 랜덤 텐서 (torch.randn):
 tensor([[ 0.5900,  0.4217, -0.3184],
        [-0.3450,  0.5313, -1.4669]])

정수 랜덤 텐서(torch.randint) :
 tensor([[1, 9, 1],
        [7, 9, 9]])

랜덤 순열(Permutation) 텐서:
 tensor([1, 9, 8, 4, 5, 3, 6, 7, 0, 2])


In [34]:
#텐서의 형태(Dimension): 3x4 (3행 4열)
#값의 범위: 모든 원소는 0과 10 사이의 랜덤 정수
#데이터 타입: int32
answer = torch.randint(0, 10, (3, 4), dtype=torch.int32)
print(answer)

tensor([[8, 8, 8, 1],
        [4, 7, 5, 5],
        [4, 9, 2, 8]], dtype=torch.int32)


# tensor의 형태 변환 


In [35]:
import torch

# 초기 텐서 생성
x = torch.arange(16)  # 0에서 15까지의 숫자를 포함하는 텐서
print("텐서:", x)
print("텐서의 형태:", x.shape)

# reshape 함수 사용 예제
reshaped_x = x.reshape(4, 4)  # 4x4 텐서로 변경
print("\n변형 후 텐서:", reshaped_x)
print("변형 후 텐서의 형태:", reshaped_x.shape)

텐서: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])
텐서의 형태: torch.Size([16])

변형 후 텐서: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])
변형 후 텐서의 형태: torch.Size([4, 4])


In [37]:
#원본 텐서의 데이터를 공유하는 새로운 형태의 텐서를 반환 
#데이터의 실제 메모리 레이아웃을 변경하지 않으며, 단지 텐서에 대한 새로운 인덱싱 뷰를 제공
#만약 원본 텐서가 메모리상에서 연속적이지 않는경우 view()를 사용할 수 없습니다. 이 경우에는 reshape()를 사용해야 합니다.
viewed_x = x.view(4, 2, 2)  # 4x2x2 텐서로 변경
print("변형 후 텐서:", viewed_x)
print("변형 후 텐서의 형태:", viewed_x.shape)

변형 후 텐서: tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]])
변형 후 텐서의 형태: torch.Size([4, 2, 2])


In [39]:
#차원 축소 
# 크기가 1인 차원을 포함하는 텐서 생성
tensor = torch.tensor([[[1, 2, 3, 4]]])  # 크기: (1, 1, 4)
print("원본 텐서:", tensor)
print("원본 텐서 형태:", tensor.shape)

# 모든 크기가 1인 차원을 제거
squeezed_tensor = tensor.squeeze()
print("\n변형된 텐서:", squeezed_tensor)
print("변형된 텐서 형태:", squeezed_tensor.shape)

# 특정 차원을 지정하여 squeeze
squeezed_dim_tensor = tensor.squeeze(0)  # 첫 번째 차원을 지정
print("\n변형된 텐서:", squeezed_dim_tensor)
print("변형된 텐서 형태:", squeezed_dim_tensor.shape)

원본 텐서: tensor([[[1, 2, 3, 4]]])
원본 텐서 형태: torch.Size([1, 1, 4])

변형된 텐서: tensor([1, 2, 3, 4])
변형된 텐서 형태: torch.Size([4])

변형된 텐서: tensor([[1, 2, 3, 4]])
변형된 텐서 형태: torch.Size([1, 4])


In [40]:
# 차원 확장 ununsqueeze() 메서드를 사용하여 크기가 1인 차원을 추가할 수 있습니다.
# 예를 들어, 1차원 텐서에 대해 차원을 확장하려면 unsqueeze()를 사용할 수 있습니다.
# 원본 텐서 생성
tensor = torch.tensor([1, 2, 3, 4])  # 크기: (4,)
print("원본 텐서:", tensor)
print("원본 텐서 형태:", tensor.shape)

# 첫 번째 차원을 추가하여 차원 확장
unsqueeze_tensor_first_dim = tensor.unsqueeze(0)
print("\n변형된 텐서:", unsqueeze_tensor_first_dim)
print("변형된 텐서 형태:", unsqueeze_tensor_first_dim.shape)

# 마지막 차원을 추가하여 차원 확장
unsqueeze_tensor_last_dim = tensor.unsqueeze(-1)
print("\n변형된 텐서:", unsqueeze_tensor_last_dim)
print("변형된 텐서 형태:", unsqueeze_tensor_last_dim.shape)

원본 텐서: tensor([1, 2, 3, 4])
원본 텐서 형태: torch.Size([4])

변형된 텐서: tensor([[1, 2, 3, 4]])
변형된 텐서 형태: torch.Size([1, 4])

변형된 텐서: tensor([[1],
        [2],
        [3],
        [4]])
변형된 텐서 형태: torch.Size([4, 1])


In [42]:
# 초기 3차원 텐서 생성
tensor = torch.rand(2, 3, 4)
print("원본 텐서:", tensor.shape)
transposed_tensor = tensor.transpose(0, 1)  # 첫 번째 차원과 두 번째 차원 교환
print("변형된 텐서 형태:", transposed_tensor.shape)


원본 텐서: torch.Size([2, 3, 4])
변형된 텐서 형태: torch.Size([3, 2, 4])


In [44]:
# permute 사용 예제
print("\n원본 텐서:", tensor.shape)
permuted_tensor = tensor.permute(2, 0, 1)  # 차원 순서를 (2, 0, 1)로 재배열
print("변형된 텐서 형태:", permuted_tensor.shape)


원본 텐서: torch.Size([2, 3, 4])
변형된 텐서 형태: torch.Size([4, 2, 3])


In [46]:
#텐서 결합 
# 두 개의 텐서 생성
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6, 7], [8, 9, 10]])

# cat 함수 사용 예제
cat_tensors = torch.cat((tensor1, tensor2), dim=1)  # 1번 차원(열)을 따라 결합
print("결합된 텐서 0:\n", cat_tensors)

print('\ntensor1 텐서 형태: ', tensor1.shape)
print('tensor2 텐서 형태: ', tensor2.shape)
print('cat_tensors 텐서 형태: ', cat_tensors.shape)

결합된 텐서 0:
 tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])

tensor1 텐서 형태:  torch.Size([2, 2])
tensor2 텐서 형태:  torch.Size([2, 3])
cat_tensors 텐서 형태:  torch.Size([2, 5])


# 텐서 결합 stack

- cat과는 다르게, 모든 텐서에 대해 새로운 차원이 생기므로, 텐서들은 그 크기가 동일해야 한다. 
- stack은 데이터를 구조적으로 정리하고 싶을 때 유용 

In [47]:
# 2x2 행렬 생성
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
tensor3 = torch.tensor([[9, 10], [11, 12]])

# stack 함수 사용 예제
stack_tensors = torch.stack((tensor1, tensor2, tensor3), dim=0)  # 새 차원을 0번 차원으로 삽입하여 쌓기

print("stack_tensors\n", stack_tensors)
print('stack_tensors 텐서 형태: ', stack_tensors.shape)

stack_tensors
 tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
stack_tensors 텐서 형태:  torch.Size([3, 2, 2])


In [48]:
#텐서 분할 
# 10개의 요소를 가진 1차원 텐서 생성
tensor = torch.arange(10)  # 0부터 9까지의 숫자
print("원본 텐서:", tensor)
print("텐서 형태:", tensor.shape)

# chunk 함수 사용 예제
chunks = torch.chunk(tensor, 3, dim=0)  # 3개의 조각으로 분할
print("\n Chunks")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}: {chunk}, {chunk.shape}")

원본 텐서: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
텐서 형태: torch.Size([10])

 Chunks
Chunk 0: tensor([0, 1, 2, 3]), torch.Size([4])
Chunk 1: tensor([4, 5, 6, 7]), torch.Size([4])
Chunk 2: tensor([8, 9]), torch.Size([2])


In [51]:
# [10, 20] 크기의 텐서 생성
tensor = torch.randn(10, 20) 

# 첫 번째 차원(길이가 10)을 기준으로, 4개와 6개 요소를 포함하는 두 조각으로 나눔
split_sizes = (4, 6)  # 조각의 크기를 지정
splits = tensor.split(split_sizes, dim=0)  # 0번째 차원(행)을 기준으로 나눔

# 나누어진 조각들 확인
print(f"첫 번째 조각의 크기: {splits[0].size()}")
print(f"두 번째 조각의 크기: {splits[1].size()}")

첫 번째 조각의 크기: torch.Size([4, 20])
두 번째 조각의 크기: torch.Size([6, 20])


# tensor indexing

- 원하는 요소에 접근할 때 사용하는 방법 


In [52]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

selected_element = tensor[1,2]  # 인덱싱: 텐서에서 특정 요소 선택
print(selected_element)

tensor(6)


In [53]:
# 0부터 시작하여 순서대로 증가하는 값을 가진 텐서 생성
# torch.arange로 0부터 24까지의 숫자를 생성하고, 이를 [5, 5] 크기로 재구성
tensor = torch.arange(0, 25).reshape(5, 5)
print("원본 텐서:\n", tensor)

sliced_tensor = tensor[:, 1:4] # 슬라이싱

print("\n슬라이스된 텐서 (모든 행, 두 번째~네 번째 열):")
print(sliced_tensor)

원본 텐서:
 tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

슬라이스된 텐서 (모든 행, 두 번째~네 번째 열):
tensor([[ 1,  2,  3],
        [ 6,  7,  8],
        [11, 12, 13],
        [16, 17, 18],
        [21, 22, 23]])


In [54]:
tensor = torch.arange(0, 25).reshape(5, 5)

mask = tensor > 5  # 조건부 인덱싱
selected_elements = tensor[mask]
print("5 이상 값:", selected_elements)

5 이상 값: tensor([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24])


# 4. 고급 인덱싱 기법 



In [55]:
#gather() 메서드를 사용하여 특정 인덱스의 값을 선택할 수 있습니다. 예를 들어, 2차원 텐서에서 특정 행과 열의 값을 선택하려면 gather()를 사용할 수 있습니다.
# 예제: 2차원 텐서에서 특정 인덱스의 값을 선택
tensor = torch.tensor([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
indices = torch.tensor([[0, 2], [1, 0], [2, 1]])  # 선택할 인덱스
gathered_elements = tensor.gather(1, indices)  #
print("선택된 요소:\n", gathered_elements)

선택된 요소:
 tensor([[10, 30],
        [50, 40],
        [90, 80]])


In [56]:
# gather 예제
y = torch.tensor([[1, 2], [3, 4]])
gather_index = torch.tensor([[0, 0], [1, 0]])
gathered = y.gather(1, gather_index)  # 지정된 인덱스에서 값을 수집
print("추출한 텐서:\n", gathered)

추출한 텐서:
 tensor([[1, 1],
        [4, 3]])


PyTorch의 gather는 인덱스 텐서가 가리키는 위치의 값을 특정 축(dim)에서 뽑아오는 함수입니다.

핵심 한 줄
- y = x.gather(dim, index)
- dim 축을 따라 index가 지정한 위치의 값을 가져오고, 결과 shape은 index와 동일합니다.

1) 꼭 알아야 할 규칙
- x와 index는 차원 수(ndim)가 같아야 합니다.
- index의 dtype은 정수형(Long, int64)이어야 합니다.
- index의 각 값은 dim 축 범위 안이어야 합니다.
- output.shape = index.shape
- dim 이외의 축에서는 index와 x가 브로드캐스트 가능한 형태여야 합니다.

2) 직관적으로 이해하기
- dim=1이면 각 행(row)에서 열(column) 인덱스를 골라 뽑습니다.
- dim=0이면 각 열(column)에서 행(row) 인덱스를 골라 뽑습니다.

3) 기본 예제 (dim=1, 행별 열 선택)
- x
  [[10, 20, 30],
   [40, 50, 60]]

- index
  [[2, 0],
   [1, 1]]

- y = x.gather(1, index)

- y
  [[30, 10],
   [50, 50]]

설명
- 첫 행: 열 2, 0 선택 → 30, 10
- 둘째 행: 열 1, 1 선택 → 50, 50

4) dim=0 예제 (열별 행 선택)
- x
  [[10, 20, 30],
   [40, 50, 60],
   [70, 80, 90]]

- index
  [[2, 1, 0],
   [0, 2, 1]]

- y = x.gather(0, index)

- y
  [[70, 50, 30],
   [10, 80, 60]]

설명
- dim=0이므로 각 위치에서 행 번호를 index가 지정함

5) 실무에서 자주 쓰는 패턴
- 분류 모델에서 정답 클래스 점수 뽑기
  - logits shape: [batch, num_classes]
  - targets shape: [batch]
  - targets를 [batch, 1]로 바꾼 뒤 gather(1, targets_unsqueezed)
  - 각 샘플의 정답 클래스 logit만 추출 가능

6) 자주 나는 에러와 해결
- 에러: index dtype이 float
  - 해결: index.long() 사용
- 에러: index out of bounds
  - 해결: index 값이 0 이상, 해당 dim 크기 미만인지 확인
- 에러: 차원 수 불일치
  - 해결: unsqueeze로 차원 맞추기
- 에러: 예상과 다른 shape
  - 해결: 결과 shape은 index shape이라는 점 확인

7) gather vs index_select 차이
- gather
  - 위치마다 다른 인덱스를 줄 수 있음(세밀함)
- index_select
  - 한 축에서 공통 인덱스만 선택(간단함)


In [57]:
# masked_select() 메서드를 사용하여 조건에 맞는 요소를 선택할 수 있습니다. 예를 들어, 2차원 텐서에서 특정 조건을 만족하는 요소를 선택하려면 masked_select()를 사용할 수 있습니다.
# 예제: 2차원 텐서에서 특정 조건을 만족하는 요소 선택
tensor = torch.tensor([1, 2, 3, 4])

# 마스크 생성
mask = torch.tensor([True, False, True, False])
selected = tensor.masked_select(mask)
print("추출한 텐서:\n", selected)

추출한 텐서:
 tensor([1, 3])


In [61]:
#정수 배열을 사용한 인덱싱 

tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 정수 배열을 사용한 인덱싱
rows = torch.tensor([0, 2]) 
cols = torch.tensor([1, 2]) 
#짝지어서 선택 됨 (0,1) (2,2) 선택됨

# 선택된 행과 열에 해당하는 요소를 추출
selected_by_index = tensor[rows, cols]

print("추출한 텐서:", selected_by_index)

selected_by_index2 = tensor[rows][:, cols]

print("추출한 텐서2:", selected_by_index2)

추출한 텐서: tensor([2, 9])
추출한 텐서2: tensor([[2, 3],
        [8, 9]])


## 5. 텐서와 넘파이간의 변환 

In [62]:
import numpy as np

# 넘파이 배열 생성
numpy_array = np.array([1, 2, 3, 4, 5])
print("넘파이 배열:", numpy_array)

# 넘파이 배열을 텐서로 변환
tensor_from_numpy = torch.from_numpy(numpy_array)
print("텐서:", tensor_from_numpy)

넘파이 배열: [1 2 3 4 5]
텐서: tensor([1, 2, 3, 4, 5])


In [63]:
# 텐서 생성
tensor = torch.tensor([1, 2, 3, 4, 5])
print("텐서:", tensor)

# 텐서를 넘파이 배열로 변환
numpy_from_tensor = tensor.numpy()
print("넘파이 배열:", numpy_from_tensor)

텐서: tensor([1, 2, 3, 4, 5])
넘파이 배열: [1 2 3 4 5]


In [64]:
# 원본 텐서 생성
original_tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)
print("텐서 원본:", original_tensor)

# 텐서 복제
cloned_tensor = original_tensor.clone()
print("복제된 텐서:", cloned_tensor)

# 복제된 텐서 수정
cloned_tensor[0] = 10
print("수정된 텐서:", cloned_tensor)

# 원본 텐서 확인 (원본 텐서는 변경되지 않음)
print("텐서 원본 확인:", original_tensor)

텐서 원본: tensor([1., 2., 3., 4., 5.])
복제된 텐서: tensor([1., 2., 3., 4., 5.])
수정된 텐서: tensor([10.,  2.,  3.,  4.,  5.])
텐서 원본 확인: tensor([1., 2., 3., 4., 5.])


In [65]:
tensor_A = torch.Tensor(
            [[0.5259, 0.1797],
            [0.1203, 0.4127],
            [0.4313, 0.2818],
            [0.4835, 0.1294],
            [0.4494, 0.8073]])

reshaped_tensor = tensor_A.reshape(2,5)
view_tensor = tensor_A.view(2,5)

## view: 
- 메모리를 복사하지 않고 기존 텐서를 다른 모양으로 “바라보는” 방식입니다. 
- 그래서 원본 텐서가 연속(contiguous) 메모리여야 합니다. 아니면 에러가 납니다.
## reshape
- 가능하면 view처럼 동작하지만, 
- 필요하면 내부적으로 복사해서라도 원하는 모양을 만들어줍니다. 그래서 더 유연합니다.

In [67]:
# (1, 5, 1) 형태의 랜덤 텐서 B 생성
tensor_B = torch.rand((1, 5, 1))

#(5,)로 축소
squeezed_tensor = tensor_B.squeeze()
print("squeezed_tensor shape:", squeezed_tensor.shape)

# (1, 5) 형태로 확장
unsqueezed_tensor = squeezed_tensor.unsqueeze(0)
print("unsqueezed_tensor shape:", unsqueezed_tensor.shape)

squeezed_tensor shape: torch.Size([5])
unsqueezed_tensor shape: torch.Size([1, 5])


In [70]:
# (3, 4) 형태의 랜덤 텐서 D1과 D2 생성
tensor_D1 = torch.rand((3, 4))
tensor_D2 = torch.rand((3, 4))

# 차원 0을 기준으로 결합
cat_tensor = torch.cat((tensor_D1, tensor_D2), dim=0)
print("cat_tensor shape:", cat_tensor.shape)

# 새로운 차원을 추가하여 결합
stack_tensor = torch.stack((tensor_D1, tensor_D2), dim=0)
print("stack_tensor shape:", stack_tensor.shape)

cat_tensor shape: torch.Size([6, 4])
stack_tensor shape: torch.Size([2, 3, 4])
