# 텐서의 기본 연산 


In [1]:
import torch

tensor = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)

# 텐서와 스칼라의 덧셈
add_scalar = tensor + 1

# 텐서와 스칼라의 뺄셈
sub_scalar = tensor - 1

# 텐서와 스칼라의 곱셈
mul_scalar = tensor * 2

# 텐서와 스칼라의 나눗셈 
div_scalar = tensor / 2

# 텐서와 스칼의 제곱
pow_scalar = tensor ** 2

print('스칼라 덧셈: \n', add_scalar)
print('스칼라 뺄셈: \n', sub_scalar)
print('스칼라 곱셈: \n', mul_scalar)
print('스칼라 나눗셈: \n', div_scalar)
print('스칼라 제곱: \n', pow_scalar)

스칼라 덧셈: 
 tensor([[2., 3.],
        [4., 5.]])
스칼라 뺄셈: 
 tensor([[0., 1.],
        [2., 3.]])
스칼라 곱셈: 
 tensor([[2., 4.],
        [6., 8.]])
스칼라 나눗셈: 
 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
스칼라 제곱: 
 tensor([[ 1.,  4.],
        [ 9., 16.]])


In [2]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# 텐서 덧셈
add_result = tensor_a + tensor_b
# 또는 torch.add(tensor_a, tensor_b)를 사용할 수 있습니다. 

# 텐서 뺄셈
sub_result = tensor_a - tensor_b
# 또는 torch.sub(tensor_a, tensor_b)를 사용할 수 있습니다.

print('덧셈 결과:\n', add_result)
print('뺄셈 결과:\n', sub_result)

덧셈 결과:
 tensor([[ 6,  8],
        [10, 12]])
뺄셈 결과:
 tensor([[-4, -4],
        [-4, -4]])


In [3]:
# 두 텐서 생성
tensor_a = torch.tensor([2, 3, 4], dtype=torch.float32)
tensor_b = torch.tensor([5, 6, 7], dtype=torch.float32)

# 요소별 곱셈
product = tensor_a * tensor_b
# 또는 torch.mul(tensor_a, tensor_b)를 사용할 수 있습니다.
print('요소별 곱셈:', product)

# 요소별 나눗셈
division = tensor_a / tensor_b
# 또는 torch.div(tensor_a, tensor_b)를 사용할 수 있습니다.
print('요소별 나눗셈:', division)

요소별 곱셈: tensor([10., 18., 28.])
요소별 나눗셈: tensor([0.4000, 0.5000, 0.5714])


# broadcasting 

- 서로 다른 모양(shape)를 가진 텐서들 간에도 수학 연산을 수행할 수 있게 됨. 
- (5,4) 와 (1, 4) 텐서의 경우 (1,4) 모양의 텐서는 첫번째 차원을 따라 5회 반복
- (5,4) 와 (4,) 모양의 경우 (1,4)로 간주 되어 수행

In [4]:
# 크기가 (1,3)인 텐서 생성
tensor_a = torch.tensor([[1, 2, 3]], dtype=torch.float32)

# 크기가 (3,)인 텐서 생성
tensor_b = torch.tensor([4, 5, 6], dtype=torch.float32)

# tensor_a와 tensor_b의 요소별 덧셈 (브로드캐스팅 발생)
# tensor_b가 tensor_a의 모양에 맞게 확장되어 연산됨
result_add = tensor_a + tensor_b

print('요소별 덧셈 결과:', result_add)

요소별 덧셈 결과: tensor([[5., 7., 9.]])


In [7]:
tensor_a = torch.tensor([1, 2, 3, 4, 5])
tensor_b = torch.tensor([1, 2, 0, 4, 5])

result = tensor_a == tensor_b
# torch.eq(tensor_a, tensor_b)를 사용할 수 있습니다.

print('동등 비교 결과:', result)

result = tensor_a != tensor_b
# torch.ne(tensor_a, tensor_b)를 사용할 수 있습니다.
print('비동등 비교 결과:', result)

result = tensor_a.eq(tensor_b)
print('동등 비교 결과 (eq 메서드):', result)

동등 비교 결과: tensor([ True,  True, False,  True,  True])
비동등 비교 결과: tensor([False, False,  True, False, False])
동등 비교 결과 (eq 메서드): tensor([ True,  True, False,  True,  True])


In [8]:
tensor_a = torch.tensor([5, 6, 7, 8])
tensor_b = torch.tensor([4, 6, 7, 10])

# 조건: a 텐서가 b텐서보다 크다
gt_result = tensor_a > tensor_b
# 또는 torch.gt(tensor_a, tensor_b)를 사용할 수 있습니다.

# 조건: a 텐서가 b텐서보다 작다.
lt_result = tensor_a < tensor_b
# 또는 torch.lt(tensor_a, tensor_b)를 사용할 수 있습니다.

print('a가 b보다 큰가:', gt_result)
print('a가 b보다 작은가:', lt_result)

a가 b보다 큰가: tensor([ True, False, False, False])
a가 b보다 작은가: tensor([False, False, False,  True])


In [9]:
# 텐서 간 요소별 대소 비교 (a >= b)
ge_result = tensor_a >= tensor_b
# 또는 torch.ge(tensor_a, tensor_b) 를 사용할 수 있습니다.

# 텐서 간 요소별 대소 비교 (a <= b)
le_result = tensor_a <= tensor_b
# 또는 torch.le(tensor_a, tensor_b) 를 사용할 수 있습니다.

print('a가 b보다 크거나 같은가:', ge_result)
print('a가 b보다 작거나 같은가:', le_result)

a가 b보다 크거나 같은가: tensor([ True,  True,  True, False])
a가 b보다 작거나 같은가: tensor([False,  True,  True,  True])


In [10]:
# 두 텐서 생성
A = torch.tensor([1, 4, 3, 2, 5])
B = torch.tensor([3, 2, 1, 5, 4])

# A의 각 요소가 B의 해당 요소보다 큰지 비교
mask = torch.gt(A, B)  # 또는 A > B

# 조건을 만족하는 A의 요소 추출
selected_elements = A[mask]

print('조건을 만족하는 A의 요소:', selected_elements)

조건을 만족하는 A의 요소: tensor([4, 3, 5])


In [11]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 전체 텐서에서 최대값 구하기
max_value = torch.max(tensor)
print('텐서 전체의 최대값:', max_value)

# 전체 텐서에서 최소값 구하기
min_value = torch.min(tensor)
print('텐서 전체의 최소값:', min_value)

# 특정 차원을 기준으로 최대값과 그 위치 구하기
max_values, max_indices = torch.max(tensor, dim=1)
print('각 행의 최대값:', max_values)
print('각 행의 최대값 위치:', max_indices)

# 특정 차원을 기준으로 최소값과 그 위치 구하기
min_values, min_indices = torch.min(tensor, dim=1)
print('각 행의 최소값:', min_values)
print('각 행의 최소값 위치:', min_indices)

텐서 전체의 최대값: tensor(9)
텐서 전체의 최소값: tensor(1)
각 행의 최대값: tensor([3, 6, 9])
각 행의 최대값 위치: tensor([2, 2, 2])
각 행의 최소값: tensor([1, 4, 7])
각 행의 최소값 위치: tensor([0, 0, 0])


In [12]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# 전체 텐서의 합계 구하기
total_sum = torch.sum(tensor)
print('텐서 전체의 합계:', total_sum)

# 각 열의 합계 구하기 (열 방향)
col_sum = torch.sum(tensor, dim=0)
print('각 열의 합계:', col_sum)

# 각 행의 합계 구하기 (행 방향)
row_sum = torch.sum(tensor, dim=1)
print('각 행의 합계:', row_sum)

텐서 전체의 합계: tensor(45)
각 열의 합계: tensor([12, 15, 18])
각 행의 합계: tensor([ 6, 15, 24])


In [13]:
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])

# 평균 구하기
mean_value = torch.mean(tensor)
print('평균:', mean_value)

# 중앙값 구하기
median_value = torch.median(tensor)
print('중앙값:', median_value)

# 최빈값 구하기
mode_value, mode_index = torch.mode(tensor)
print('최빈값:', mode_value)
print('최빈값의 인덱스:', mode_index)

평균: tensor(5.)
중앙값: tensor(5.)
최빈값: tensor(1.)
최빈값의 인덱스: tensor(0)


In [14]:
# 임의의 텐서 생성
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0], dtype=torch.float32)

# 분산 구하기
variance = torch.var(tensor)
print('분산:', variance)

# 표준편차 구하기
standard_deviation = torch.std(tensor)
print('표준편차:', standard_deviation)

분산: tensor(2.5000)
표준편차: tensor(1.5811)


In [15]:
tensor_a = torch.tensor([True, False, True, False], dtype=torch.bool)
tensor_b = torch.tensor([True, True, False, False], dtype=torch.bool)

# 요소별 AND 연산 수행
result_and = tensor_a & tensor_b
# 또는 torch.logical_and(tensor_a, tensor_b) 를 사용할 수 있습니다.

print('AND 연산 결과:', result_and)

AND 연산 결과: tensor([ True, False, False, False])


In [16]:
# 요소별 OR 연산 수행
result_or = tensor_a | tensor_b
# 또는 torch.logical_or(tensor_a, tensor_b) 를 사용할 수 있습니다.

print('OR 연산 결과:', result_or)

OR 연산 결과: tensor([ True,  True,  True, False])


In [17]:
# 요소별 NOT 연산 수행
result_not = ~tensor_a
# 또는 torch.logical_not(tensor_a) 를 사용할 수 있습니다.

print('NOT 연산 결과:', result_not)

NOT 연산 결과: tensor([False,  True, False,  True])


In [18]:
# 임의의 텐서 생성
tensor = torch.tensor([1.0, 2.0, 3.0, 4.0])

# 지수 연산
exp_result = torch.exp(tensor)
print('지수 연산 결과:', exp_result)

# 로그 연산
log_result = torch.log(tensor)
print('로그 연산 결과:', log_result)

# 제곱근 연산
sqrt_result = torch.sqrt(tensor)
print('제곱근 연산 결과:', sqrt_result)

지수 연산 결과: tensor([ 2.7183,  7.3891, 20.0855, 54.5982])
로그 연산 결과: tensor([0.0000, 0.6931, 1.0986, 1.3863])
제곱근 연산 결과: tensor([1.0000, 1.4142, 1.7321, 2.0000])


In [19]:
# 임의의 텐서 생성
tensor = torch.tensor([1.0, -2.0, 3.0, -4.0])

# 제곱 연산
squared = torch.pow(tensor, exponent=2)
print('제곱 결과:', squared)

# 절대값 연산
abs_values = torch.abs(tensor)
print('절대값 결과:', abs_values)

# 역수 연산
reciprocal = torch.reciprocal(tensor)
print('역수 결과:', reciprocal)

# 음수 연산
neg = torch.neg(tensor)
print('음수 결과:', neg)

제곱 결과: tensor([ 1.,  4.,  9., 16.])
절대값 결과: tensor([1., 2., 3., 4.])
역수 결과: tensor([ 1.0000, -0.5000,  0.3333, -0.2500])
음수 결과: tensor([-1.,  2., -3.,  4.])


In [20]:
# 라디안 단위의 각도 텐서 생성
angles = torch.tensor([0, torch.pi/6, torch.pi/4, torch.pi/3, torch.pi/2])

# 사인 연산
sin_values = torch.sin(angles)
print('사인 값:', sin_values)

# 코사인 연산
cos_values = torch.cos(angles)
print('코사인 값:', cos_values)

# 탄젠트 연산
tan_values = torch.tan(angles)
print('탄젠트 값:', tan_values)

사인 값: tensor([0.0000, 0.5000, 0.7071, 0.8660, 1.0000])
코사인 값: tensor([ 1.0000e+00,  8.6603e-01,  7.0711e-01,  5.0000e-01, -4.3711e-08])
탄젠트 값: tensor([ 0.0000e+00,  5.7735e-01,  1.0000e+00,  1.7321e+00, -2.2877e+07])


In [ ]:
a_data = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
b_data = [[10, 11, 12],
          [13, 14, 15],
          [16, 17, 18]]

A = torch.tensor(a_data)
B = torch.tensor(b_data)

answer = 3*torch.log(A) + torch.sin(2*B) - 1
print(answer)

tensor([[-0.0871,  1.0706,  1.3903],
        [ 3.9214,  4.0992,  3.3872],
        [ 5.3892,  5.7674,  4.5999]])


In [22]:
a_data = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
A = torch.tensor(a_data)

answer = (A > 2) & (A <= 8)
print(answer)

tensor([[False, False,  True],
        [ True,  True,  True],
        [ True,  True, False]])


In [23]:
a_data = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]
A = torch.tensor(a_data)

mask = (A > 2) & (A <= 8)
answer = A[mask]
print(answer)

tensor([3, 4, 5, 6, 7, 8])
