# Activate Function

$ x1w1 + x2w2 + b = a $ -> $ h(a) = y $

In [1]:
import torch
import torch.nn as nn

# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

In [2]:
# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("Input Tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nLinear Layer Output:\n", linear_output)

# 시그모이드 활성화 함수 적용
sigmoid_output = torch.sigmoid(linear_output)
print("\nSigmoid Output:\n", sigmoid_output)

Input Tensor:
 tensor([[-0.2432, -1.0418, -0.6822, -1.1456, -0.3105,  0.4148,  0.1592,  1.8900,
          0.2511, -0.9999]])

Linear Layer Output:
 tensor([[0.8118]], grad_fn=<AddmmBackward0>)

Sigmoid Output:
 tensor([[0.6925]], grad_fn=<SigmoidBackward0>)


## 탄젠트 함수 적용

- 탄젠트 함수는 출력 값을 -1과 1사이로 압축. 이는 데이터를 중심으로 정규화할때 유용 

In [5]:
# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("Input Tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nLinear Layer Output:\n", linear_output)

# 하이퍼볼릭 탄젠트 활성화 함수 적용
tanh_output = torch.tanh(linear_output)
print("\nTanh Output:\n", tanh_output)

Input Tensor:
 tensor([[-1.2554,  1.7565, -0.5585, -0.0607,  0.4171, -0.3252,  0.3420, -0.5106,
         -0.2085,  0.2635]])

Linear Layer Output:
 tensor([[-1.4311]], grad_fn=<AddmmBackward0>)

Tanh Output:
 tensor([[-0.8919]], grad_fn=<TanhBackward0>)


## ReLU(Recitified Linear Unit )

- ReLU 함수는 음수 입력을 0으로 바꾼다. 모델의 학습 속도를 개선하고, 그래디언트 소실 문제를 줄이는데 도움을 줌 

In [6]:
# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

# ReLU 활성화 레이어 정의
relu_layer = nn.ReLU()

# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("Input Tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nLinear Layer Output:\n", linear_output)

# ReLU 레이어를 통과
relu_output = relu_layer(linear_output)
print("\nReLU Layer Output:\n", relu_output)

Input Tensor:
 tensor([[-0.6369, -0.4262, -0.1697, -0.8971, -0.0316,  1.4341, -0.6611,  0.2440,
         -0.0178, -0.9893]])

Linear Layer Output:
 tensor([[-0.2613]], grad_fn=<AddmmBackward0>)

ReLU Layer Output:
 tensor([[0.]], grad_fn=<ReluBackward0>)


## LeakyReLU

- ReLU와 유사하지만, 음수 입력에 대해 매우 작은 양의 기울기를 허용하여 뉴런이 죽는 문제를 완화 

In [7]:
# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

# LeakyReLU 활성화 레이어 정의 (기울기 0.01)
leaky_relu = nn.LeakyReLU(negative_slope=0.01) # 음수 부분의 기울기를 0.01로 설정 

# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("input_tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nlinear_output:\n", linear_output)

# LeakyReLU 레이어를 통과
leaky_relu_output = leaky_relu(linear_output)
print("\nLeaky ReLU Output:\n", leaky_relu_output)

input_tensor:
 tensor([[ 0.5831,  0.4220,  0.1822, -0.2363, -0.0093,  0.3617, -1.3777, -0.3696,
         -1.2258, -1.2732]])

linear_output:
 tensor([[0.1875]], grad_fn=<AddmmBackward0>)

Leaky ReLU Output:
 tensor([[0.1875]], grad_fn=<LeakyReluBackward0>)


# softmax

- softmax함수는 다중 클래스 분류 문제에서 출력 값을 확률 분포로 변환. 주로 `출력레이어`에서 사용

In [8]:
# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

# Softmax 활성화 레이어 정의 (dim 파라미터는 softmax를 적용할 차원)
softmax = nn.Softmax(dim=1)

# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("input_tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nlinear_output:\n", linear_output)

# Softmax 레이어를 통과
softmax_output = softmax(linear_output)
print("\nSoftmax Output:\n", softmax_output)

input_tensor:
 tensor([[-0.5551, -0.1936,  1.0335,  1.3241, -0.7585,  0.9280, -1.3579,  0.3189,
         -0.6229, -0.3099]])

linear_output:
 tensor([[0.3394]], grad_fn=<AddmmBackward0>)

Softmax Output:
 tensor([[1.]], grad_fn=<SoftmaxBackward0>)


# LogSoftmax

- 로그소프트맥스 함수는 다중 클래스 분류 문제에서 softmax 함수의 로그 값을 계산. 
- 이 함수는 주로 학습 과정에서 크로스 엔트로피 손실과 함께 사용되어 계산을 단순화 하고 수치적 안정성을 높인다 `출력레이어` 또는, `손실 계산 전에` 사용됨. 

In [9]:
# 선형 층 정의 (입력 특성 10개, 출력 특성 1개)
linear_layer = nn.Linear(in_features=10, out_features=1)

# Softmax 활성화 레이어 정의 (dim 파라미터는 softmax를 적용할 차원)
softmax = nn.LogSoftmax(dim=1)

# 임의의 입력 텐서 생성 (배치 크기 1, 입력 특성 10개)
input_tensor = torch.randn(1, 10)
print("input_tensor:\n", input_tensor)

# 선형 층을 통과
linear_output = linear_layer(input_tensor)
print("\nlinear_output:\n", linear_output)

# Softmax 레이어를 통과
softmax_output = softmax(linear_output)
print("\nSoftmax Output:\n", softmax_output)

input_tensor:
 tensor([[ 0.6561,  0.9313,  0.6486,  2.2122, -1.1010, -2.1638,  2.1165,  0.4756,
         -0.0246, -0.9471]])

linear_output:
 tensor([[-1.0044]], grad_fn=<AddmmBackward0>)

Softmax Output:
 tensor([[0.]], grad_fn=<LogSoftmaxBackward0>)


## Dropout Layers

- 드랍아웃이란 학습 과정에서 신경망의 뉴런(노드)를 무작위로 선택하여 활성화하지 않음으로써, 즉 해당 뉴런의 출력을 0으로 만듦으로써 작동 
- 마치 신경망 내에서 여러 가지 다른 구조의 신경망이 학습되는 효과를 낳아, 모델이 특정 뉴런이나 뉴런의 조합에 과도하게 의존하는 것을 방지 

- Overfitting을 방지하는 효과적인 방법중 하나. 
- `과적합`이란 모델이 학습데이터에 너무 잘 맞춰져서 새로운 데이터나 테스트 데이터에 대한 성능이 떨어지는 현상. 

In [10]:
# 드랍아웃 객체 생성, 드랍아웃 비율을 50%로 설정
dropout = nn.Dropout(p=0.5)

# 입력 데이터 텐서 생성
input_data = torch.randn(1, 10)  # 1x10 크기의 랜덤 텐서

# 드랍아웃 적용
output = dropout(input_data)

print("Input data:\n", input_data)
print("\nAfter applying dropout:\n", output)

Input data:
 tensor([[ 0.8316, -1.1715,  1.1120,  0.4128,  0.0182, -0.8769,  3.3423, -0.4448,
          1.3513,  1.3352]])

After applying dropout:
 tensor([[ 1.6632, -2.3431,  0.0000,  0.0000,  0.0000, -1.7538,  6.6847, -0.0000,
          2.7026,  0.0000]])


# Model 만들기 

- sequencial container 

- 여러 모듈을 순서대로 쌓아 올릴 수 있게 해주며, 데이터가 정의된 순서대로 각 모듈을 통과 

In [12]:
# Sequential 모델 정의
model = nn.Sequential(
    ### 여기에 모델 상세 내용을 작성하세요.
    nn.Linear(784, 128), # 입력층 -> 첫번째 은닉층
    nn.ReLU(), #첫 번째 은닉층의 활성화 함수
    nn.Dropout(p=0.2),#20% 확률로 드랍아웃
    nn.Linear(128, 64), # 128개의 뉴런, 64개의 뉴런으로 전달
    nn.ReLU(),
    nn.Linear(64, 10), #0~9사이의 숫자를 분류, 분류 문제이므로, 활성화 함수로는 LogSoftmax를 사용
    nn.LogSoftmax(dim=1)
)

# 모델 구조 출력
print(model)

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.2, inplace=False)
  (3): Linear(in_features=128, out_features=64, bias=True)
  (4): ReLU()
  (5): Linear(in_features=64, out_features=10, bias=True)
  (6): LogSoftmax(dim=1)
)


In [13]:
class CustomModel(nn.Module):
    def __init__(self):
        super(CustomModel, self).__init__()
        # 첫 번째 은닉층: 784개의 입력 특성을 받아 128개의 뉴런으로 전달
        self.fc1 = nn.Linear(784, 128)
        self.relu1 = nn.ReLU()  # 첫 번째 은닉층의 활성화 함수로 ReLU 정의

        # 두 번째 은닉층: 128개의 뉴런을 받아 64개의 뉴런으로 전달
        self.fc2 = nn.Linear(128, 64)
        self.relu2 = nn.ReLU()  # 두 번째 은닉층의 활성화 함수로 ReLU 정의

        # 출력층: 64개의 뉴런을 받아 10개의 출력을 생성
        self.fc3 = nn.Linear(64, 10)

        # 드랍아웃 적용: 확률은 20%
        self.dropout = nn.Dropout(p=0.2)

    def forward(self, x):
        # 첫 번째 은닉층을 통과한 후 ReLU 활성화 함수 적용
        x = relu1(fc1(x))
        
        # 드랍아웃 적용
        x = dropout(x)
        
        # 두 번째 은닉층을 통과한 후 ReLU 활성화 함수 적용
        x = self.relu2(self.fc2(x))
        
        # 출력층을 통과
        x = self.fc3(x)
        
        # 최종 출력을 위해 Softmax 적용
        return nn.Softmax(dim=1)(x)

model = CustomModel()
model

CustomModel(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (relu1): ReLU()
  (fc2): Linear(in_features=128, out_features=64, bias=True)
  (relu2): ReLU()
  (fc3): Linear(in_features=64, out_features=10, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)