# torch.nn.Functional

- pyTorch에서 제공하는 모듈 중 하나로, 신경망을 구축할 때 필요한 다양한 함수를 포함. 
- 활성화 함수, 손실 함수, 컨볼루션 연산 등 신경망의 기본 구성 요소가 함수 형태로 제공 

- 함수형 인터페이스를 제공, 주로 상태를 갖지 않는 레이어나 연산에 사용 
- 코드에서 직접적으로 연산을 수행하고자 할 때 유용 
    - 임의ㅏ의 데이터 변환을 수행하거나 커스텀 손실 함수를 정의할 때 사용할 수 있다. 
- 더 세밀한 제어가 필요하거나, 특정 연산을 한번만 수행하고자 할 때 적합

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# 임의의 입력 데이터를 생성합니다. 여기서는 3개의 특성을 가진 데이터 한 개를 예로 들겠습니다.
input_data = torch.rand(1, 3)

# 가중치와 바이어스를 직접 정의합니다. 가중치는 [출력 차원 x 입력 차원]의 크기를, 바이어스는 출력 차원의 크기를 가집니다.
weight = torch.rand(2, 3) # 출력 차원이 2, 입력 차원이 3인 가중치
bias = torch.rand(2)  # 출력 차원에 해당하는 바이어스

# F.linear 함수를 사용하여 연산을 수행합니다.
output = F.linear(input_data, weight, bias)

print('\nW: \n', weight)
print('x: \n', input_data)
print('\nb: \n', bias)
print('\noutput: \n', output)


W: 
 tensor([[0.3602, 0.8411, 0.5391],
        [0.3701, 0.0373, 0.5893]])
x: 
 tensor([[0.2801, 0.5678, 0.4536]])

b: 
 tensor([0.5403, 0.4863])

output: 
 tensor([[1.3633, 0.8784]])


# torch.nn.functional의 구성 

|분류|이름|설명|PyTorch code|
|---|---|---|---|
|활성화 함수|ReLU|음수 값을 0으로 만들고 양수값은 그대로 유지하는 비선형 함수| F.relu(x)|
||Sigmoid|출력을 0과 1사이로 압축하는 S형 곡선함수|F.sigmoid(x)|
||Tanh|출력을 -1과 1사이로 압축하는 하ㅣ퍼볼릭 탄젠트 함수| F.tanh(x)|
|손실 함수|MSE loss|평균 제곱 오차 손실, 회귀 문제에서 주로 사용| F.mse_los(input,target)|
||Cross Entropy Loss|크로스 엔트로피 손실, 분류 문제에서 사용되며, 실제 분포와 예측 분포 사이의 차이를 측정|F.cross_entropy(input, target)|
|완전 연결|Linear|각 입력에 가중치를 곱하고 결과를 합한 후 바이어스를 더하는 선형 변환|F.linear(input,weight,bias= None) |
|컨볼루션 연산|Cov2d|2차원 데이터 에 대한 컨볼루션 연산을 수행, 주로 이미지에서 패턴 인식에 사용|F.conv2d(input,weight)|
|폴링 연산|Max Pooling|최대 풀링은 입력 영역에서 최대 값을 선택하여 출력의 차원을 줄임|F.max_pool2d(x, kernel_size)|
||Average Pooling| 평균 풀링은 입력 영역의 평균 갑을 계산하여 출력의 차원을 줄임| F.avg_pool2d(x, kernel_size)|
|정규화 함수|BatchNorm|배치 정규화는 미니배치의 평균과 분산을 사용하여 내부 공변량 변화를 줄이는 기술| F.batch_norm(input)|
|드롭아웃|Dropout|드롭아웃은 특정 뉴런을 임의로 활성화하지 않음으로써 과적합을 방지하는 기술| F.dropout(x, p)|

In [5]:
# 임의의 입력 데이터 생성: 배치 크기 1, 채널 1, 높이 5, 너비 5
input_data = torch.rand(1, 1, 5, 5)

# 컨볼루션 커널(가중치) 정의: 출력 채널 1, 입력 채널 1, 커널 크기 3x3
weight = torch.rand(1, 1, 3, 3)

# 선택적으로 바이어스 정의: 출력 채널 1에 대한 바이어스
bias = torch.rand(1)

# F.conv2d 함수를 사용하여 2D 컨볼루션 수행
output = F.conv2d(input_data, weight, bias, stride=1, padding=1)
# stride는 “얼마나 건너뛰며 볼지”
# padding은 “가장자리를 얼마나 보완할지” 입니다.
print(output)

tensor([[[[1.4189, 1.5180, 1.6064, 1.3000, 0.8346],
          [1.5754, 2.1754, 1.9035, 1.8826, 1.1091],
          [1.7642, 2.1588, 2.1557, 1.6635, 1.1617],
          [1.3096, 1.7481, 1.7476, 1.6208, 1.3149],
          [0.9628, 1.0279, 1.1909, 0.9999, 0.8289]]]])


In [4]:
# 임의의 입력 데이터 생성: 음수와 양수 값을 모두 포함
input_data = torch.tensor([-1.0, -0.5, 0.0, 0.5, 1.0])

# F.relu 함수를 사용하여 ReLU 활성화 함수 적용
output = F.relu(input_data)

print(output)

tensor([0.0000, 0.0000, 0.0000, 0.5000, 1.0000])


In [6]:
input_tensor = torch.randn(3, 3)
print('인풋 텐서: \n', input_tensor)

# 모델을 학습할 때는 training=True로 적용해 줍니다
output1 = F.dropout(input_tensor, p=0.5, training=True)
print('\n학습모드: \n', output1)

# 모델을 학습하지 않을 때는 training=False로 적용해 줍니다
output2 = F.dropout(input_tensor, p=0.5, training=False)
print('\n예측모드: \n',output2)

인풋 텐서: 
 tensor([[ 0.2298, -0.5090,  0.2766],
        [-2.0477, -1.1256, -0.1268],
        [-1.8605,  0.0246,  0.2835]])

학습모드: 
 tensor([[ 0.4597, -1.0180,  0.5531],
        [-4.0954, -0.0000, -0.2536],
        [-3.7209,  0.0000,  0.5669]])

예측모드: 
 tensor([[ 0.2298, -0.5090,  0.2766],
        [-2.0477, -1.1256, -0.1268],
        [-1.8605,  0.0246,  0.2835]])


## nn.Parameter

- PyTorch에서 학습 가능한 매개변수를 나타내는 데 사용되는 특별한 종류의 텐서 
- 신경망에서 학습 가능한 매개변수란 모델 학습 과정 중에 최적화되는 변수, 즉, 모델의 가중치와 바이어스를 말한다. 

- `nn.Parameter`는 torch.Tensor를 상속받으며, nn.Module내에서 사용 될 때 자동으로 모듈의 매개변수로 등록 된다. 

In [ ]:
class SimpleLinearModel(nn.Module):
    def __init__(self, input_size, output_size):
        super(SimpleLinearModel, self).__init__()
        # 가중치와 바이어스를 nn.Parameter로 직접 정의합니다.
        # torch.randn함수를 이용해 초기값을 랜덤으로 넣어줍니다.
        self.weight = nn.Parameter(torch.randn(output_size, input_size))
        self.bias = nn.Parameter(torch.randn(output_size))

    def forward(self, x):
        # 정의된 가중치와 바이어스를 사용하여 선형 변환을 수행합니다.
        return F.linear(x, self.weight, self.bias)

# 모델 인스턴스를 생성합니다.
model = SimpleLinearModel(input_size=10, output_size=2)


print('델의 매개변수 이름과 크기를 확인합니다. ==========')
for name, param in model.named_parameters():
    print(f'{name}: {param.size()}')

print('\n매개변수에 들어있는 값을 확인해 봅시다. ==========')
for param in model.parameters():
    print(param)

1. nn.Parameter는 그냥 Tensor가 아니라 “학습 대상 텐서”라는 표식이 붙은 타입입니다.  
2. Module 안에서 self.weight = nn.Parameter(...)처럼 속성에 할당하면, nn.Module.__setattr__가 이를 감지해서 내부 _parameters 딕셔너리에 등록합니다.  
3. model.parameters()는 이 _parameters(그리고 하위 서브모듈의 _parameters) 를 순회해서 반환합니다.  
4. 그래서 코드에서 self.weight, self.bias를 nn.Parameter로 선언한 순간, optimizer가 접근 가능한 “학습 파라미터 집합”에 자동 포함됩니다.

반대로:
- self.weight = torch.randn(...)처럼 일반 Tensor로 넣으면 _parameters에 등록되지 않아서 model.parameters()에 안 잡힙니다.
- 결과적으로 optimizer가 업데이트하지 못합니다.

즉, “Parameter로 선언 + Module 속성으로 할당” 이 두 조건이 충족되어야 parameters()로 접근 가능한 이유입니다.

# 문제7

- 모델은 nn.Module을 상속받아야 합니다.
- 모델은 입력층, 하나의 은닉층, 그리고 출력층을 포함해야 합니다.
- 은닉층과 출력층 사이에는 드롭아웃을 적용해야 합니다. 드롭아웃 비율은 0.5로 설정하세요.
- 은닉층의 활성화 함수로는 ReLU를 사용해야 합니다.
- init 메소드 내에서 은닉층과 출력층의 가중치 및 바이어스를 nn.Parameter를 사용하여 정의해야 - 합니다.
- 모델은 입력 크기가 10, 은닉층 크기가 5, 출력 크기가 2인 구조를 가져야 합니다.
- forward 메소드를 구현하여 데이터가 모델을 통과하는 방식을 정의해야 합니다.
- forward 메소드 내에서는 nn.functional.linear을 사용하여 선형 변환을 수행하고, nn.- functional.dropout을 사용하여 드롭아웃을 적용해야 합니다.

In [7]:
class SimpleNeuralNetwork(torch.nn.Module):
    def __init__(self, input_size, hidden_size, output_size, dropout_rate=0.5):
        super(SimpleNeuralNetwork, self).__init__()
        # 첫 번째 완전 연결층의 가중치와 바이어스를 정의합니다.
        self.weight1 = nn.Parameter(torch.randn(hidden_size, input_size))
        self.bias1 = nn.Parameter(torch.randn(hidden_size))
        
        # 두 번째 완전 연결층의 가중치와 바이어스를 정의합니다.
        self.weight2 = nn.Parameter(torch.randn(output_size, hidden_size))
        self.bias2 = nn.Parameter(torch.randn(output_size))
        
        # 드롭아웃 비율
        self.dropout_rate = dropout_rate

    def forward(self, x):
        # 첫 번째 완전 연결층을 통과한 후 ReLU 활성화 함수를 적용합니다.
        x = nn.ReLU(nn.functional.linear(x, weight1, bias1))
        # 드롭아웃 적용
        x = nn.Dropout(x, p=dropout_rate, training=self.training)
        # 두 번째 완전 연결층을 통과합니다.
        x = nn.functional.linear(x,weight2,bias2)
        return x

# 모델 인스턴스를 생성합니다. 드롭아웃 비율은 0.5로 설정합니다.
model = SimpleNeuralNetwork(input_size=10, hidden_size=5, output_size=2, dropout_rate=0.5)
print(model)

SimpleNeuralNetwork()
