# 사용자 정의 연산

- x : 입력 벡터, shape = (in_features, 1)
- W : 가중치 행렬, shape = (out_features, in_features)
- b : 바이어스 벡터, shape = (out_features,) 또는 (out_features, 1)
- 즉, x는 열벡터이며, 연산은 W @ x + b 형태로 수행합니다.

In [2]:
import torch

def custom_layer(x, weight, bias): 
    '''
    여기에 연산을 적용해 보세요.
    '''
    x = torch.matmul(weight, x) + bias
    return x

# 예제 입력 데이터
input_tensor = torch.randn(10, 1)

# 가중치와 바이어스 초기화
weight = torch.randn(2, 10)
bias = torch.randn(2)

# 함수형 레이어 사용
output = custom_layer(input_tensor, weight, bias)
print("Custom Layer input shape:", input_tensor.shape)
print("Custom Layer output shape:", output.shape)
print(output)

Custom Layer input shape: torch.Size([10, 1])
Custom Layer output shape: torch.Size([2, 2])
tensor([[-1.9843, -1.4290],
        [ 3.7901,  4.3454]])


# 문제3

$$
y = \sin{(xW^{T})} + b
$$

In [13]:
def custom_sine_layer(x, weight, bias):
    '''
    여기에 연산을 적용해 보세요.
    '''
    x = torch.sin(torch.matmul(x, weight.t())) + bias
    return x
torch.manual_seed(42) 
# 예제 입력 데이터
input_tensor = torch.randn(1, 10)
# 가중치와 바이어스 초기화
weight = torch.randn(2, 10)
bias = torch.randn(1)

# 함수형 레이어 사용
output = custom_sine_layer(input_tensor, weight, bias)
output

tensor([[-0.9500,  0.7207]])

In [12]:
def custom_sine_layer(x, weight, bias):
    # 가중치와 입력의 행렬 곱
    x = torch.matmul(x, weight.t())
    # Sine 함수 적용
    x = torch.sin(x)
    # 스칼라 바이어스 추가
    x = x + bias
    return x
torch.manual_seed(42) 
# 예제 입력 데이터
input_tensor = torch.randn(1, 10)
# 가중치와 바이어스 초기화
weight = torch.randn(2, 10)
bias = torch.randn(1)

# 함수형 레이어 사용
output = custom_sine_layer(input_tensor, weight, bias)
output

tensor([[-0.9500,  0.7207]])

In [16]:
import torch.nn as nn

class CustomLinearLayer(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(CustomLinearLayer, self).__init__()
        # 가중치의 차원을 [output_dim, input_dim]으로 수정합니다.
        self.weight = nn.Parameter(torch.randn(output_dim, input_dim))
        self.bias = nn.Parameter(torch.randn(output_dim))
        
    def forward(self, x):
        # 입력 x와 가중치의 전치를 곱한 다음 편향을 더합니다.
        y = x @ self.weight.t() + self.bias
        return y

# 레이어 사용 예시
input_dim = 5
output_dim = 3

# 사용자 정의 레이어 인스턴스 생성
custom_layer = CustomLinearLayer(input_dim, output_dim)

# 입력 텐서 생성
x = torch.randn(2, input_dim) # 배치 사이즈 2

# 레이어를 통과한 결과
y = custom_layer(x)

print(y)  # 결과 출력

tensor([[-0.9507, -2.3397, -0.1659],
        [ 0.7520, -0.8081,  2.9521]], grad_fn=<AddBackward0>)


In [18]:
import torch.nn.functional as F

class CustomMLP(nn.Module):
    def __init__(self):
        super(CustomMLP, self).__init__()
        self.fc1 = CustomLinearLayer(20, 50)
        self.fc2 = CustomLinearLayer(50, 30)
        self.fc3 = CustomLinearLayer(30, 3)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        x = self.fc3(x)
        return x
    
# 모델 초기화
model = CustomMLP()

# 배치 크기 5, 입력 크기 20인 임의의 입력 데이터
x = torch.randn(5, 20)

# 모델을 통과하여 예측 수행
output = model(x)

print("모델의 예측 출력:\n", output)
print("출력 크기:", output.size())

모델의 예측 출력:
 tensor([[ -71.7566, -153.7779,  147.4306],
        [  88.6033, -181.9898,   98.9551],
        [   9.2206,  -97.4978,   19.1507],
        [-231.1799, -147.6172,  310.9202],
        [ -37.4268,  -24.3240,   53.5061]], grad_fn=<AddBackward0>)
출력 크기: torch.Size([5, 3])
