In [1]:
import torch

# 벡터 정의
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

# 벡터의 내적 계산
dot_product = vector1 @ vector2
# 또는 torch.dot(vector1, vector2) 로 내적을 계산할 수 있다.

print("벡터의 내적 결과:", dot_product)

벡터의 내적 결과: tensor(32)


In [2]:
# 두 개의 2x2 행렬을 정의합니다.
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# 행렬 곱셈 연산을 수행합니다.
mul_matrix = torch.matmul(matrix1, matrix2)

print("행렬 matrix1:\n", matrix1)
print("행렬 matrix2:\n", matrix2)
print("matrix1와 matrix2의 곱 mul_matrix:\n", mul_matrix)

행렬 matrix1:
 tensor([[1, 2],
        [3, 4]])
행렬 matrix2:
 tensor([[5, 6],
        [7, 8]])
matrix1와 matrix2의 곱 mul_matrix:
 tensor([[19, 22],
        [43, 50]])


In [3]:
matrix_A = torch.tensor([[4, 7], [2, 6]], dtype=torch.float32)

# 행렬식 계산
det_A = torch.linalg.det(matrix_A)

print(f"A 행렬의 행렬식: {det_A}")
print('직접 계산: ', 4 * 6 - 7 * 2)

A 행렬의 행렬식: 10.000000953674316
직접 계산:  10


In [4]:
# 3x3 행렬 정의
matrix_B = torch.tensor(
    [[1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9]], dtype=torch.float32)

# 행렬식 계산
det_B = torch.linalg.det(matrix_B)
print(f"B 행렬의 행렬식: {det_B}")

B 행렬의 행렬식: 0.0


In [5]:
# 가역적인 2x2 행렬 정의
matrix_A = torch.tensor([[4.0, 7.0], [2.0, 6.0]])

# 역행렬 계산
matrix_inv = torch.linalg.inv(matrix_A)

print("matrix_A 행렬:\n", matrix_A)
print("matrix_A의 역행렬:\n", matrix_inv)

matrix_A 행렬:
 tensor([[4., 7.],
        [2., 6.]])
matrix_A의 역행렬:
 tensor([[ 0.6000, -0.7000],
        [-0.2000,  0.4000]])


In [6]:
# A x A-1 가 항등 행렬인지 확인해 봅시다.
torch.matmul(matrix_A, matrix_inv)

tensor([[1.0000e+00, 8.9407e-08],
        [2.9802e-08, 1.0000e+00]])

In [7]:
# A-1 x A 가 항등 행렬인지 확인해 봅시다.
torch.matmul(matrix_inv, matrix_A)

tensor([[1.0000e+00, 4.7684e-07],
        [0.0000e+00, 1.0000e+00]])

In [8]:
matrix = torch.tensor(
    [[1, 2, 3], 
      [4, 5, 6], 
      [7, 8, 9]], dtype=torch.float32)

det = torch.linalg.det(matrix)
print(f"행렬의 행렬식: {det}")

행렬의 행렬식: 0.0


In [9]:
try:
    torch.linalg.inv(matrix)
except Exception as e:
    print(e) # 행렬식이 0일때, 역행렬을 구하면 에러가 발생하는 것을 확인할 수 있음.

### 1. 트레이스 (Trace, 대각합)

트레이스는 행렬의 왼쪽 위에서 오른쪽 아래로 이어지는 **주대각선(Main Diagonal) 성분들을 모두 더한 값**입니다. 기호로는 $\operatorname{tr}(A)$라고 씁니다.

**[기본 공식]**


$$A$$

가 

$$n \times n$$

 정방행렬일 때,


$$\operatorname{tr}(A) = \sum_{i=1}^n a_{ii} = a_{11} + a_{22} + \dots + a_{nn}$$

**[특이한 성질]**
트레이스는 계산은 유치원생도 할 만큼 쉽지만, 그 성질은 매우 기이합니다.

* **순서 무시 (Cyclic Property):** 행렬의 곱셈은 원래 교환법칙이 성립하지 않아서 $AB \neq BA$입니다. 하지만 신기하게도 **트레이스를 씌우면 순서를 바꿔 곱해도 그 합이 완전히 똑같습니다.** 
$$\operatorname{tr}(AB) = \operatorname{tr}(BA)$$


* **고윳값의 합:** 행렬이 가진 고유한 에너지 같은 값인 '고윳값(Eigenvalues, $\lambda$)'들을 모두 더하면, 놀랍게도 트레이스 값과 정확히 일치합니다.

$$\operatorname{tr}(A) = \lambda_1 + \lambda_2 + \dots + \lambda_n$$



---

### 2. 행렬식 (Determinant)

행렬식은 이 행렬(변환 규칙)이 "공간의 부피를 몇 배로 팽창/수축시키는가?"를 나타내는 절대적인 지표입니다. 행렬식이 0이면 공간이 납작하게 찌그러져(차원 축소) 복원이 불가능해집니다. 기호로는 $\det(A)$ 또는 $|A|$로 씁니다.

**[2x2 행렬식]**


$$\det\begin{pmatrix} a & b \\ c & d \end{pmatrix} = ad - bc$$

**[행렬식의 일반화 식 (라이프니츠 공식)]**
크기가 커지면 식은 기하급수적으로 복잡해집니다. $n \times n$ 행렬의 일반화된 행렬식은 '순열(Permutation)'을 이용해 다음과 같이 씁니다.


$$\det(A) = \sum_{\sigma \in S_n} \operatorname{sgn}(\sigma) \prod_{i=1}^n a_{i, \sigma(i)}$$


*이 수식은 수학적으로는 아름답지만, 팩토리얼($n!$)의 계산량을 요구하기 때문에 컴퓨터조차 $100 \times 100$ 행렬에 이 공식을 그대로 대입하면 우주가 멸망할 때까지 계산을 끝내지 못합니다.*

**[라플라스 전개 (여인수 전개)]**
그래서 실무에서는 차원을 하나씩 깎아내려 가는 아래의 점화식을 사용하여 계산합니다.


$$\det(A) = \sum_{j=1}^n (-1)^{i+j} a_{ij} M_{ij}$$


*(여기서 $M_{ij}$는 $i$행과 $j$열을 지우고 남은 더 작은 행렬의 행렬식입니다.)*

---

### 3. 행렬의 세계를 관통하는 특이하고 소름 돋는 공식들

행렬식과 트레이스, 그리고 고윳값들이 서로 얽히면서 만들어내는 아주 유명하고 특이한 식들입니다. 딥러닝 고급 논문이나 양자역학 등에서 불쑥불쑥 튀어나오는 무기들입니다.

#### ① 고윳값과의 비밀스러운 관계

트레이스가 고윳값의 합이었다면, 행렬식은 고윳값들의 '곱'과 같습니다. 즉, 행렬의 대각합과 부피 비율은 결국 고윳값이라는 하나의 뿌리에서 나옵니다.


$$\det(A) = \prod_{i=1}^n \lambda_i = \lambda_1 \times \lambda_2 \times \dots \times \lambda_n$$

#### ② 케일리-해밀턴 정리 (Cayley-Hamilton Theorem)

"모든 정방행렬은 자기 자신을 근으로 삼는 방정식(특성 방정식)을 만족한다"는 놀라운 정리입니다. 특히 $2 \times 2$ 행렬 $A$에 대해서는, 오직 앞서 배운 트레이스와 행렬식만으로 자기 자신의 거듭제곱을 통제하는 방정식을 만들어냅니다.


$$A^2 - \operatorname{tr}(A)A + \det(A)I = 0$$


*(여기서 $I$는 단위 행렬, $0$은 영행렬입니다. 행렬의 제곱을 곱셈 없이 덧셈만으로 강등시켜 버리는 마법 같은 식입니다.)*

#### ③ 실베스터의 행렬식 정리의 변형 (야코비 공식, Matrix Exponential)

덧셈과 곱셈의 세계를 지수함수 위로 끌어올린 끝판왕 공식 중 하나입니다. 자연상수 $e$의 지수 자리에 숫자 대신 '행렬'을 얹었을 때, 행렬식과 트레이스가 기적처럼 연결됩니다.


$$\det(e^A) = e^{\operatorname{tr}(A)}$$


이 공식 덕분에 복잡한 행렬식의 미분 계산을 훨씬 다루기 쉬운 트레이스의 덧셈 미분으로 바꿔치기할 수 있으며, 이 테크닉은 머신러닝의 확률 모델(연속 시간 마르코프 체인 등)을 풀 때 강력한 치트키로 사용됩니다.

In [10]:
# 정사각 행렬 정의
A = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]], dtype=torch.float)

# 행렬의 트레이스 계산
trace_A = torch.trace(A)
print(f"A 행렬의 추적: {trace_A}")

A 행렬의 추적: 15.0


In [11]:
import torch

# 행렬 A 정의
A = torch.tensor([[4.0, 1.0], [2.0, 3.0]])

# 고유값과 고유벡터 계산
eigenvalues, eigenvectors = torch.linalg.eig(A)

print("행렬 A의 고유값:")
print(eigenvalues)
print("행렬 A의 고유벡터:")
print(eigenvectors)

행렬 A의 고유값:
tensor([5.+0.j, 2.+0.j])
행렬 A의 고유벡터:
tensor([[ 0.7071+0.j, -0.4472+0.j],
        [ 0.7071+0.j,  0.8944+0.j]])


# 특이값 분해 (SVD, Singular Value Decomposition)

In [12]:
A = torch.tensor([[3.0, 2.0, 2.0], [2.0, 3.0, -2.0]], dtype=torch.float32)

# A텐서에서 특이값 분해를 해 봅시다.
U, S, V = torch.linalg.svd(A, full_matrices=False)

print("행렬 A:\n", A)
print("U 행렬:\n", U)
print("특이값(Σ) 대각 행렬:\n", torch.diag(S))
print("V^T 행렬:\n", V.transpose(0, 1))

행렬 A:
 tensor([[ 3.,  2.,  2.],
        [ 2.,  3., -2.]])
U 행렬:
 tensor([[-0.7071, -0.7071],
        [-0.7071,  0.7071]])
특이값(Σ) 대각 행렬:
 tensor([[5.0000, 0.0000],
        [0.0000, 3.0000]])
V^T 행렬:
 tensor([[-0.7071, -0.2357],
        [-0.7071,  0.2357],
        [ 0.0000, -0.9428]])


In [13]:
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])

answer = A.matmul(torch.linalg.inv(B))
print(answer)

tensor([[ 3.0000, -2.0000],
        [ 2.0000, -1.0000]])


In [14]:
A = torch.tensor([[4.0, 11.0, 14.0],
                  [8.0, 7.0, -2.0]])

U, S, Vt = torch.linalg.svd(A)

print('U: \n', U)
print('S: \n', S)
print('Vt: \n', Vt)

U: 
 tensor([[-0.9487, -0.3162],
        [-0.3162,  0.9487]])
S: 
 tensor([18.9737,  9.4868])
Vt: 
 tensor([[-0.3333, -0.6667, -0.6667],
        [ 0.6667,  0.3333, -0.6667],
        [-0.6667,  0.6667, -0.3333]])
