# 다항식 (Polynominal) 피처 생성의 정의와 목적

- 기존 피처들을 사용하여 그 피처들의 고차항(제고브 세제곱 등)과 피처 간의 상호작용 항을 추가함으로써 새로운 피처 셋을 만드는 기법 
- 피처들의 복잡한 패ㅓㄴ과 비선형 관계를 포착할 수 있는 정보를 모델에 제공 

## 상관관계 행렬 계산하기 

```python
features_analysis = ['HouseAge', 'AveRooms', 'target']

# 상관관계 행렬 계산
correlation_matrix = housing_df[features_analysis].corr()
print(correlation_matrix['target'])
```

## corr 사용 방법

- 대표적인 method는 아래 3가지입니다.

```python
corr_matrix = df.corr(method="pearson", numeric_only=True)
```

### pearson

- 선형 관계를 볼 때 가장 기본적으로 사용합니다.

### spearman
- 값의 크기 순서 기준 관계를 보고 싶을 때 사용합니다.

### kendall

- 순위 기반 상관관계를 더 엄격하게 보고 싶을 때 사용합니다.

## Sckit-learn 을 이용한 다항식 피처 생성

- `PolynomialFeatures` 생성은 선형 모델을 사용하여 비선형 관계를 모델링 할 때 유용 
  - 기존 피처의 다항식 조합을 쉽게 생성할 수 있다. 

```python
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.arrange(6).reshape(3,2)
print("Original feature:\n", X )

poly = PolynomialFeatures(degree=2) #다항식 피처 변환기 인스턴스 생성, degree=2 는 2차 다항식을 의미 
X_poly = poly.fit_transform(X) #다항식 피처로 변환 
```

```python
import pandas as pd 
train_solar = pd.read_csv('train_solar.csv')

train_solar_type = train_solar.dtypes 

display(train_solar.head())
display(train_solar_type)
```



- [PolynomialFeatures](./2.1.1%20PolynomialFeatures.md) 설명

In [1]:
# fit transform 

from sklearn.preprocessing import StandardScaler
import numpy as np

X = np.array([[1], [2], [3], [4]])

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print(X_scaled)

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]


In [3]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

X = np.array([[2, 3], [4, 5]])

poly = PolynomialFeatures(degree=2)
X_poly = poly.fit_transform(X)

print(X_poly)

[[ 1.  2.  3.  4.  6.  9.]
 [ 1.  4.  5. 16. 20. 25.]]


In [ ]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

train_solar_x = train_solar.drop(['ID', 'TARGET'], axis=1)

poly = PolynomialFeatures(degree=2, include_bias=False)

features_poly = poly.fit_transform(train_solar_x)
features_names = poly.get_feature_names_out(input_features=train_solar_x.columns)

# PolynomialFeatures로 생성된 피처들을 포함하는 새로운 DataFrame 생성
train_solar_poly_df = pd.DataFrame(features_poly, columns=features_names)
display(features_names)
display(train_solar_poly_df.head()) 

# 생성 된 피처들의 target과의 상관 관계 분석 

```python
train_solar_poly_df['TARGET'] = train_solar['TARGET']  

correlation_matrix = train_solar_poly_df.corr()
correlation_matrix['TARGET'].abs().sort_values()
display(correlation_matrix['TARGET'])
```