In [3]:
import torch 
import torch.nn as nn

feature_map = torch.tensor([[[
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12],
    [13, 14, 15, 16, 17, 18],
    [19, 20, 21, 22, 23, 24],
    [25, 26, 27, 28, 29, 30],
    [31, 32, 33, 34, 35, 36]
]]], dtype=torch.float)

print(feature_map.shape)  # 출력: torch.Size([1, 1, 6, 6])

torch.Size([1, 1, 6, 6])


In [4]:
max_pool_layer = nn.MaxPool2d(kernel_size=2, stride=2)
pooled_feature_map = max_pool_layer(feature_map)

print('Original Feature Map:')
print(feature_map[0, 0])  # 첫 번째 채널의 피처맵 출력
print('Pooled Feature Map:')
print(pooled_feature_map[0, 0])  # 풀링된 피처맵 출력

Original Feature Map:
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36.]])
Pooled Feature Map:
tensor([[ 8., 10., 12.],
        [20., 22., 24.],
        [32., 34., 36.]])


In [5]:
Avg_pool_layer = nn.AvgPool2d(kernel_size=2, stride=2)
pooled_feature_map = Avg_pool_layer(feature_map)

print('Original Feature Map:')
print(feature_map[0, 0])  
print('Pooled Feature Map:')
print(pooled_feature_map[0, 0]) 

Original Feature Map:
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.],
        [13., 14., 15., 16., 17., 18.],
        [19., 20., 21., 22., 23., 24.],
        [25., 26., 27., 28., 29., 30.],
        [31., 32., 33., 34., 35., 36.]])
Pooled Feature Map:
tensor([[ 4.5000,  6.5000,  8.5000],
        [16.5000, 18.5000, 20.5000],
        [28.5000, 30.5000, 32.5000]])


In [7]:
import numpy as np
import matplotlib.pyplot as plt

# 빨간색 채널
red_channel = np.array([
    [1, 2, 0, 2, 1],
    [0, 1, 1, 0, 0],
    [1, 0, 2, 0, 1],
    [0, 1, 1, 2, 0],
    [1, 0, 1, 0, 0]
])

# 녹색 채널
green_channel = np.array([
    [0, 1, 1, 0, 1],
    [0, 2, 1, 1, 0],
    [0, 0, 2, 0, 1],
    [0, 0, 1, 1, 0],
    [1, 0, 2, 2, 0]
])

# 파란색 채널
blue_channel = np.array([
    [1, 0, 2, 0, 1],
    [0, 0, 0, 1, 1],
    [1, 0, 2, 1, 2],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 2, 0]
])

# 3차원 입력 배열
image_color = np.stack((red_channel, green_channel, blue_channel), axis=-1)

# 필터의 각 채널
filter_red_channel = np.array([[1, 0], [0, 1]])
filter_green_channel = np.array([[1, 2], [0, 1]])
filter_blue_channel = np.array([[2, 0], [0, 0]])

# 3차원 필터 배열
filter_color = np.stack((filter_red_channel, filter_green_channel, filter_blue_channel), axis=-1)

In [8]:
input_tensor = torch.tensor(image_color, dtype=torch.float).unsqueeze(0).permute(0, 3, 1, 2)

filter_tensor = torch.tensor(filter_color, dtype=torch.float).unsqueeze(0)  
filter_tensor = filter_tensor.permute(0,3,1,2) 

conv_layer = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=2)

with torch.no_grad():
    conv_layer.weight = nn.Parameter(filter_tensor)
    conv_layer.bias = nn.Parameter(torch.zeros(1)) 

output_tensor = conv_layer(input_tensor)

print('Output shape after convolution:', output_tensor.shape)
print('Output tensor after convolution:', output_tensor)

Output shape after convolution: torch.Size([1, 1, 4, 4])
Output tensor after convolution: tensor([[[[ 8.,  7.,  6.,  4.],
          [ 4.,  9.,  4.,  5.],
          [ 4.,  6., 11.,  4.],
          [ 2.,  6.,  8.,  3.]]]], grad_fn=<ConvolutionBackward0>)


In [9]:
# Convolution 결과에 Max Pooling 적용 
max_pool_layer = nn.MaxPool2d(kernel_size=2, stride=2)
output_tensor_max_pool = max_pool_layer(output_tensor)

print('Output shape after max pooling:', output_tensor_max_pool.shape)
print('Output tensor after max pooling:', output_tensor_max_pool)

Output shape after max pooling: torch.Size([1, 1, 2, 2])
Output tensor after max pooling: tensor([[[[ 9.,  6.],
          [ 6., 11.]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


In [10]:
avg_pool_layer = nn.AvgPool2d(kernel_size=2, stride=2)
output_tensor_avg_pool = avg_pool_layer(output_tensor)
                                        
print('Output shape after average pooling:', output_tensor_avg_pool.shape)
print('Output tensor after average pooling:', output_tensor_avg_pool)

Output shape after average pooling: torch.Size([1, 1, 2, 2])
Output tensor after average pooling: tensor([[[[7.0000, 4.7500],
          [4.5000, 6.5000]]]], grad_fn=<AvgPool2DBackward0>)
