In [1]:
import torch
import torch.nn as nn

x = torch.rand(1, 3, 5, 5) # 1개의 샘플(batch), 3개의 채널(channel), 5x5 크기의 값을  가지는 랜덤 텐서를 생성

flatten = nn.Flatten() #레이어는 입력 텐서를 평탄화하는데 사용된다. 
x_flattened = flatten(x) #x를 Flatten 레이어를 통해 변환합니다. 

print("Original shape:", x.shape)
print("Original data:", x)
print("Flattened shape:", x_flattened.shape)
print("Flattened data:", x_flattened)

Original shape: torch.Size([1, 3, 5, 5])
Original data: tensor([[[[0.2418, 0.9811, 0.5065, 0.2552, 0.6274],
          [0.3868, 0.8686, 0.6736, 0.9234, 0.0060],
          [0.7543, 0.5507, 0.9035, 0.9917, 0.1648],
          [0.3937, 0.5174, 0.0386, 0.4113, 0.1962],
          [0.5783, 0.9389, 0.3289, 0.9145, 0.8661]],

         [[0.6998, 0.7306, 0.4622, 0.3876, 0.9047],
          [0.9398, 0.2255, 0.1440, 0.7250, 0.2413],
          [0.4138, 0.3333, 0.8205, 0.2131, 0.7165],
          [0.0998, 0.1932, 0.4571, 0.4178, 0.0650],
          [0.6888, 0.9552, 0.8974, 0.8838, 0.8512]],

         [[0.6752, 0.1523, 0.2270, 0.6031, 0.5757],
          [0.1352, 0.1470, 0.8775, 0.8507, 0.1200],
          [0.9552, 0.9662, 0.0613, 0.9488, 0.8742],
          [0.8036, 0.6509, 0.8573, 0.3931, 0.5489],
          [0.4504, 0.1325, 0.0790, 0.8829, 0.6365]]]])
Flattened shape: torch.Size([1, 75])
Flattened data: tensor([[0.2418, 0.9811, 0.5065, 0.2552, 0.6274, 0.3868, 0.8686, 0.6736, 0.9234,
         0.0060, 0.7543

## Fully Connected Layer

In [2]:
fc_layer = nn.Linear(in_features=75, out_features=3)#평탄화 된 텐서의 차원수와 일치 해야함. 
activation = nn.ReLU()  

output = activation(fc_layer(x_flattened))  

print(output) 

tensor([[0.0000, 0.0031, 0.0000]], grad_fn=<ReluBackward0>)


In [4]:
#완전 연결 레이어 층이 2개인 경우 
fc_layer1 = nn.Linear(in_features=75, out_features=20)  
fc_layer2 = nn.Linear(in_features=20, out_features=3)   
activation = nn.ReLU()  

output1 = activation(fc_layer1(x_flattened))  
output2 = fc_layer2(output1)  # 두 번째 완전 연결 레이어를 적용합니다.

print(output2)  

tensor([[-0.2123, -0.2460, -0.1517]], grad_fn=<AddmmBackward0>)


# Softmax function



In [6]:
import torch.nn.functional as F

fc_layer1 = nn.Linear(in_features=75, out_features=40)  
fc_layer2 = nn.Linear(in_features=40, out_features=20)
fc_layer3 = nn.Linear(in_features=20, out_features=3)   
activation = nn.ReLU()  # 활성화 함수로 ReLU 사용

output1 = activation(fc_layer1(x_flattened)) 
output2 = activation(fc_layer2(output1))       
output3 = fc_layer3(output2)                   

probabilities = F.softmax(output3, dim=1)

print("Probabilities:", probabilities)
print("Sum of probabilities:", torch.sum(probabilities))
print("softmax value sum: ", torch.sum(probabilities).item())  # .item()을 사용하여 스칼라 값으로 변환

Probabilities: tensor([[0.3340, 0.3059, 0.3601]], grad_fn=<SoftmaxBackward0>)
Sum of probabilities: tensor(1., grad_fn=<SumBackward0>)
softmax value sum:  1.0


## reference 

- [Softmax reference](../tip/softmax.md). 

# 3D 이미지와 필터를 텐서로 구현 

In [9]:
import numpy as np
import matplotlib.pyplot as plt

# 빨간색 채널
red_channel = np.array([
    [1, 2, 0, 2, 1],
    [0, 1, 1, 0, 0],
    [1, 0, 2, 0, 1],
    [0, 1, 1, 2, 0],
    [1, 0, 1, 0, 0]
])

# 녹색 채널
green_channel = np.array([
    [0, 1, 1, 0, 1],
    [0, 2, 1, 1, 0],
    [0, 0, 2, 0, 1],
    [0, 0, 1, 1, 0],
    [1, 0, 2, 2, 0]
])

# 파란색 채널
blue_channel = np.array([
    [1, 0, 2, 0, 1],
    [0, 0, 0, 1, 1],
    [1, 0, 2, 1, 2],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 2, 0]
])

# 필터의 각 채널
filter_red_channel = np.array([[1, 0], [0, 1]])
filter_green_channel = np.array([[1, 2], [0, 1]])
filter_blue_channel = np.array([[2, 0], [0, 0]])

# 3차원 입력 배열
image_color = np.stack((red_channel, green_channel, blue_channel), axis=-1)
filter_color = np.stack((filter_red_channel, filter_green_channel, filter_blue_channel), axis=-1)

print(filter_color)
print(f"image color shape: {image_color.shape}")
print(f"filter color shape: {filter_color.shape}")


[[[1 1 2]
  [0 2 0]]

 [[0 0 0]
  [1 1 0]]]
image color shape: (5, 5, 3)
filter color shape: (2, 2, 3)


In [10]:
input_tensor = torch.tensor(image_color, dtype=torch.float).unsqueeze(0).permute(0, 3, 1, 2)
# channel-first 형식으로 변환 (batch, channel, height, width)
filter_tensor = torch.tensor(filter_color, dtype=torch.float).unsqueeze(0)  
filter_tensor = filter_tensor.permute(0,3,1,2) 

conv_layer = nn.Conv2d(in_channels=1, out_channels=1, kernel_size=2)
#Conv2d 레이어를 생성하고, 입력 채널 수와 출력 채널 수를 1로 설정하고, 커널 크기를 2로 설정합니다.
with torch.no_grad():
    conv_layer.weight = nn.Parameter(filter_tensor)
    conv_layer.bias = nn.Parameter(torch.zeros(1)) 
#conv_layer의 가중치와 편향을 설정합니다. 가중치는 filter_tensor로 설정하고, 편향은 0으로 초기화합니다.
output_tensor = conv_layer(input_tensor)
#conv_layer를 사용하여 input_tensor에 대해 합성곱 연산을 수행하고, 결과를 output_tensor에 저장합니다.
print('Output shape after convolution:', output_tensor.shape)
print('Output tensor after convolution:', output_tensor)

#max pooling layer를 생성하고, kernel_size와 stride를 2로 설정합니다. 2x2 영역에서 최대값을 추출하고, stride를 2로 설정하여 겹치지 않게 이동합니다.
# moving window 방식으로 입력 텐서를 슬라이딩하면서 최대값을 추출합니다.
max_pool_layer = nn.MaxPool2d(kernel_size=2, stride=2)
output_tensor_max_pool = max_pool_layer(output_tensor)

print('Output shape after max pooling:', output_tensor_max_pool.shape)
print('Output tensor after max pooling:', output_tensor_max_pool)

Output shape after convolution: torch.Size([1, 1, 4, 4])
Output tensor after convolution: tensor([[[[ 8.,  7.,  6.,  4.],
          [ 4.,  9.,  4.,  5.],
          [ 4.,  6., 11.,  4.],
          [ 2.,  6.,  8.,  3.]]]], grad_fn=<ConvolutionBackward0>)
Output shape after max pooling: torch.Size([1, 1, 2, 2])
Output tensor after max pooling: tensor([[[[ 9.,  6.],
          [ 6., 11.]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)


# 완전 연결층이 3개인 경우

In [11]:
# Flatten 적용
flatten = nn.Flatten()
flattened = flatten(output_tensor_max_pool)

# 완전 연결 레이어 정의
fc1 = nn.Linear(in_features=4, out_features=50)  
fc2 = nn.Linear(in_features=50, out_features=20)  
fc3 = nn.Linear(in_features=20, out_features=10)  
fc4 = nn.Linear(in_features=10, out_features=3)   

# 활성화 함수
relu = nn.ReLU()
softmax = nn.Softmax()

# 은닉층을 통한 전파
hidden_output1 = relu(fc1(flattened))      # 첫 번째 완전 연결 레이어와 ReLU 활성화
hidden_output2 = relu(fc2(hidden_output1)) # 두 번째 완전 연결 레이어와 ReLU 활성화
hidden_output3 = relu(fc3(hidden_output2)) # 세 번째 완전 연결 레이어와 ReLU 활성화
output = softmax(fc4(hidden_output3))      # 최종 완전 연결 레이어와 소프트맥스 활성화

print("Flattened input:\n", flattened)
print("\nHidden layer output shape:\n", hidden_output3.shape)
print("\nFinal output shape:\n", output.shape)
print("\nFinal output (probabilities):\n", output)

Flattened input:
 tensor([[ 9.,  6.,  6., 11.]], grad_fn=<ViewBackward0>)

Hidden layer output shape:
 torch.Size([1, 10])

Final output shape:
 torch.Size([1, 3])

Final output (probabilities):
 tensor([[0.3431, 0.2852, 0.3716]], grad_fn=<SoftmaxBackward0>)


/Users/donghun2/workspace/machine_learning/dacon/.venv/lib/python3.12/site-packages/torch/nn/modules/module.py:1778: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return self._call_impl(*args, **kwargs)
